CREATE TABLE `department_assigns` (  `id` varchar(13) COLLATE utf8_unicode_ci NOT NULL,  `user_id` varchar(13) COLLATE utf8_unicode_ci NOT NULL,  `department_id` varchar(13) COLLATE utf8_unicode_ci NOT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
INSERT INTO `department_assigns` VALUES('59d0e4c00e085', '59ce8bf6ac404', '59d0d8ee1f3d8');
INSERT INTO `department_assigns` VALUES('59d0e4ccdd7ca', '59ce8f96cb791', '59d0d8ee1f3d8');
INSERT INTO `department_assigns` VALUES('59d0e4d5a7357', '59ce8fb1c799d', '59d0d8fd83056');
INSERT INTO `department_assigns` VALUES('59d0e4da78d45', '59ce8c0a10306', '59d0d8fd83056');
INSERT INTO `department_assigns` VALUES('59d0e4e011eb8', '59ce8fc91e63d', '59d0d8fd83056');
INSERT INTO `department_assigns` VALUES('59d0e4ec1f21a', '59ce8fb7b46e1', '59d0d8fa5bbe4');
INSERT INTO `department_assigns` VALUES('59d0e4f35a878', '59ce8fe52e82b', '59d0d8fa5bbe4');
INSERT INTO `department_assigns` VALUES('59d0e4f8a57d0', '59ce8fdd5657c', '59d0d8fa5bbe4');
INSERT INTO `department_assigns` VALUES('59d0e4ff5a8ec', '59ce8fd2cbe9a', '59d0d9011158f');
INSERT INTO `department_assigns` VALUES('59d0e50625be3', '59ce8fbe46f7f', '59d0d9011158f');
INSERT INTO `department_assigns` VALUES('59d0e50b54521', '59ce8c11b145c', '59d0d904d5e45');
INSERT INTO `department_assigns` VALUES('59d0e51442d68', '59ce8f9eaba3a', '59d0d904d5e45');
INSERT INTO `department_assigns` VALUES('59d0e51837a90', '59ce8f96cb791', '59d0d904d5e45');
INSERT INTO `department_assigns` VALUES('59d0e5224c58f', '59ce8f9eaba3a', '59d0d908d4e0b');
INSERT INTO `department_assigns` VALUES('59d0e558e9650', '59ce8c0a10306', '59d0d908d4e0b');
INSERT INTO `department_assigns` VALUES('59d0e55ff1d2e', '59ce8fa616a11', '59d0d90c86c3b');
INSERT INTO `department_assigns` VALUES('59d0e5657ab82', '59ce8fbe46f7f', '59d0d90c86c3b');
INSERT INTO `department_assigns` VALUES('59f0d507e3c15', '59ce8c11b145c', '59d0d9011158f');
INSERT INTO `department_assigns` VALUES('5a0c332b1f6e9', '59ce8fa616a11', '59d0d8ee1f3d8');
CREATE TABLE `departments` (  `id` varchar(13) COLLATE utf8_unicode_ci NOT NULL,  `department` varchar(100) COLLATE utf8_unicode_ci NOT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
INSERT INTO `departments` VALUES('59d0d8ee1f3d8', 'Einkauf');
INSERT INTO `departments` VALUES('59d0d8fa5bbe4', 'Konstruktion');
INSERT INTO `departments` VALUES('59d0d8fd83056', 'Produktion');
INSERT INTO `departments` VALUES('59d0d9011158f', 'Marketing');
INSERT INTO `departments` VALUES('59d0d904d5e45', 'Administration');
INSERT INTO `departments` VALUES('59d0d908d4e0b', 'Buchhaltung');
INSERT INTO `departments` VALUES('59d0d90c86c3b', 'Verkauf');
CREATE TABLE `discount_codes` (  `id` varchar(13) NOT NULL,  `code` varchar(100) NOT NULL,  `discount_type` varchar(50) NOT NULL,  `discount_amount` int(10) NOT NULL,  `code_limit` int(11) NOT NULL,  `max_products` int(5) NOT NULL,  `allowed_products` varchar(200) NOT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `email_recievers` (  `id` varchar(13) COLLATE utf8_unicode_ci NOT NULL,  `user_id` varchar(13) COLLATE utf8_unicode_ci NOT NULL,  `mail_id` varchar(13) COLLATE utf8_unicode_ci NOT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `emails` (  `id` varchar(13) COLLATE utf8_unicode_ci NOT NULL,  `email` varchar(100) COLLATE utf8_unicode_ci NOT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `graduating` (  `id` varchar(13) COLLATE utf8_unicode_ci NOT NULL,  `product_id` varchar(13) COLLATE utf8_unicode_ci NOT NULL,  `amount` int(11) NOT NULL,  `price_per_item` float NOT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
INSERT INTO `graduating` VALUES('5abb5e8cb405e', '5abb5e8cb2d93', '1', '0');
CREATE TABLE `items` (  `id` varchar(13) COLLATE utf8_unicode_ci NOT NULL,  `name` varchar(200) COLLATE utf8_unicode_ci NOT NULL,  `number` varchar(50) COLLATE utf8_unicode_ci NOT NULL,  `description` text COLLATE utf8_unicode_ci NOT NULL,  `unit` varchar(10) COLLATE utf8_unicode_ci NOT NULL,  `price` float NOT NULL,  `price_per_amt` int(5) NOT NULL,  `order_size` int(5) NOT NULL,  `material` varchar(20) COLLATE utf8_unicode_ci NOT NULL,  `weight` float NOT NULL,  `geometry` varchar(20) COLLATE utf8_unicode_ci NOT NULL,  `size` varchar(100) COLLATE utf8_unicode_ci NOT NULL,  `comment` text COLLATE utf8_unicode_ci NOT NULL,  `alert_amt` int(5) NOT NULL,  `stock` int(5) NOT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
INSERT INTO `items` VALUES('5abb5e27e6773', 'Widerstand', 'WEA-RES2k2', 'Wirderstand 2,2kO', 'Stk.', '0', '0', '0', 'Sonstiges', '0', 'Zylinder', '0', '', '0', '0');
INSERT INTO `items` VALUES('5abb5e4eadfe8', 'Transistor 2N2222', 'WEA-TRS2N2222', 'Transistor NPN 2N2222', 'Stk.', '0', '0', '0', 'Holz', '0', 'Würfel', '0', '', '0', '0');
CREATE TABLE `language_lib` (  `keyword` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `DE` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `EN` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  PRIMARY KEY (`keyword`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
INSERT INTO `language_lib` VALUES('', '', '');
INSERT INTO `language_lib` VALUES(' Kommentare/Hinweise f&uuml;r ihre Bestellung hier hinterlassen', 'Kommentare/Hinweise f&uuml;r ihre Bestellung hier hinterlassen', ' Leave comments / notes for your order here');
INSERT INTO `language_lib` VALUES(' Sie erhalten ihren Gutschein per E-Mail zugesendet.', ' Sie erhalten ihren Gutschein per E-Mail zugesendet.', 'You will receive your voucher by e-mail.');
INSERT INTO `language_lib` VALUES('&Ouml;sterreich', '&Ouml;sterreich', 'Austria');
INSERT INTO `language_lib` VALUES('&Uuml;bersicht', '&Uuml;bersicht', 'Overview');
INSERT INTO `language_lib` VALUES('&Uuml;berweisung', '&Uuml;berweisung', 'Transaction');
INSERT INTO `language_lib` VALUES('1', '1', '');
INSERT INTO `language_lib` VALUES('Österreich', 'Österreich', 'Austria');
INSERT INTO `language_lib` VALUES('Abbrechen', 'Abbrechen', 'Cancel');
INSERT INTO `language_lib` VALUES('Abgeschlossen', 'Abgeschlossen', 'Finished');
INSERT INTO `language_lib` VALUES('Abmaße', 'Abmaße', 'Size');
INSERT INTO `language_lib` VALUES('Abmelden', 'Abmelden', 'Logout');
INSERT INTO `language_lib` VALUES('Abmessungen', 'Abmessungen', 'Size');
INSERT INTO `language_lib` VALUES('Absenden', 'Absenden', 'Send');
INSERT INTO `language_lib` VALUES('Absolut', 'Absolut', 'Absolute');
INSERT INTO `language_lib` VALUES('Abstand Links', 'Abstand Links', 'Dist. Left');
INSERT INTO `language_lib` VALUES('Abstand Oben', 'Abstand Oben', 'Dist. Top');
INSERT INTO `language_lib` VALUES('Abstempeln', 'Abstempeln', 'Stamp off');
INSERT INTO `language_lib` VALUES('Abteilungen', 'Abteilungen', 'Department');
INSERT INTO `language_lib` VALUES('Abteilungszugeh&ouml;rigkeit Eintragen', 'Abteilungszugeh&ouml;rigkeit Eintragen', 'Enter Department-Assignation');
INSERT INTO `language_lib` VALUES('Abteilungszuweisung', 'Abteilungszuweisung', 'Department Assign');
INSERT INTO `language_lib` VALUES('Account', 'Account', 'Account');
INSERT INTO `language_lib` VALUES('Achtung: Passwort bei erstem Login: \"123abc\". Bitte gleich nach Anmelden unter \"Account\" &auml;ndern!', 'Achtung: Passwort bei erstem Login: \"123abc\". Bitte gleich nach Anmelden unter \"Account\" &auml;ndern!', 'Attention: Password at first login: \"123abc\". Please change immediately after login under \"Account\"!');
INSERT INTO `language_lib` VALUES('Admin', 'Admin', 'Admin');
INSERT INTO `language_lib` VALUES('Administration', 'Administration', 'Administration');
INSERT INTO `language_lib` VALUES('aktuell', 'aktuell', 'currently');
INSERT INTO `language_lib` VALUES('Aktuelle Arbeitszeit', 'Aktuelle Arbeitszeit', 'Current working Time');
INSERT INTO `language_lib` VALUES('Aktueller Lagerbestand', 'Aktueller Lagerbestand', 'Available Stock');
INSERT INTO `language_lib` VALUES('Alle Abteilungen', 'Alle Abteilungen', 'All Departments');
INSERT INTO `language_lib` VALUES('Alle anzeigen', 'Alle anzeigen', 'Show all');
INSERT INTO `language_lib` VALUES('Alle Bestellungen', 'Alle Bestellungen', 'All Orders');
INSERT INTO `language_lib` VALUES('Alle Stempelzeiten', 'Alle Stempelzeiten', 'All Timestamps');
INSERT INTO `language_lib` VALUES('Als ausstehend markieren', 'Als ausstehend markieren', 'Mark as pending');
INSERT INTO `language_lib` VALUES('Als erledigt markieren', 'Als erledigt markieren', 'Mark as done');
INSERT INTO `language_lib` VALUES('Aluminium', 'Aluminium', 'Aluminium');
INSERT INTO `language_lib` VALUES('Anfrage abschicken', 'Anfrage abschicken', 'Send Request');
INSERT INTO `language_lib` VALUES('Anfragen / Verbesserungsvorschläge', 'Anfragen / Verbesserungsvorschläge', 'Requests');
INSERT INTO `language_lib` VALUES('Angebot schreiben', 'Angebot schreiben', 'Write offer');
INSERT INTO `language_lib` VALUES('Angebote', 'Angebote', 'Offers');
INSERT INTO `language_lib` VALUES('Angemeldet als', 'Angemeldet als', 'Signed in as');
INSERT INTO `language_lib` VALUES('Angestempelt seit', 'Angestempelt seit', 'Stamped in since');
INSERT INTO `language_lib` VALUES('Anmelden', 'Anmelden', 'Log in');
INSERT INTO `language_lib` VALUES('Anmerkung', 'Anmerkung', 'Comment');
INSERT INTO `language_lib` VALUES('Anrede', 'Anrede', 'Salutation');
INSERT INTO `language_lib` VALUES('Anschrift', 'Anschrift', 'Adress');
INSERT INTO `language_lib` VALUES('Anstempeln', 'Anstempeln', 'Stamp in');
INSERT INTO `language_lib` VALUES('Anzeigen', 'Anzeigen', 'Show');
INSERT INTO `language_lib` VALUES('Übersicht', 'Übersicht', 'Overview');
INSERT INTO `language_lib` VALUES('Überweisung', 'Überweisung', 'Transfer');
INSERT INTO `language_lib` VALUES('Arbeitszeit wird nicht angerechnet', 'Arbeitszeit wird nicht angerechnet', 'Worktime is not added');
INSERT INTO `language_lib` VALUES('Arbeitszeiten unter 10s werden nicht angerechnet', 'Arbeitszeiten unter 10s werden nicht angerechnet', 'Working hours under 10s are not counted');
INSERT INTO `language_lib` VALUES('Artikel', 'Artikel', 'Article');
INSERT INTO `language_lib` VALUES('Artikel Anlegen', 'Artikel Anlegen', 'Add Item');
INSERT INTO `language_lib` VALUES('Artikel auswählen', 'Artikel auswählen', 'Choose items');
INSERT INTO `language_lib` VALUES('Artikel Hinzufügen', 'Artikel Hinzufügen', 'Add Item');
INSERT INTO `language_lib` VALUES('Artikel Hinzufügen/Entfernen', 'Artikel Hinzufügen/Entfernen', 'Add/Remove item');
INSERT INTO `language_lib` VALUES('Artikel L&ouml;schen', 'Artikel L&ouml;schen', 'Delete item');
INSERT INTO `language_lib` VALUES('Artikel-Bezeichnung', 'Artikel-Bezeichnung', 'Item-Description');
INSERT INTO `language_lib` VALUES('Artikel-Name', 'Artikel-Name', 'Item-Name');
INSERT INTO `language_lib` VALUES('Artikel-Nr', 'Artikel-Nr', 'Item-Nr');
INSERT INTO `language_lib` VALUES('Artikel-Nummer', 'Artikel-Nummer', 'Item-Number');
INSERT INTO `language_lib` VALUES('Auftrag Löschen', 'Auftrag Löschen', 'Delete Order');
INSERT INTO `language_lib` VALUES('Auftraggeber', 'Auftraggeber', 'Customer');
INSERT INTO `language_lib` VALUES('Auftrags-Nr', 'Auftrags-Nr', 'Order-Nr');
INSERT INTO `language_lib` VALUES('Ausstehend', 'Ausstehend', 'Pending');
INSERT INTO `language_lib` VALUES('Barzahlung', 'Barzahlung', 'Cash');
INSERT INTO `language_lib` VALUES('Bearbeiten', 'Bearbeiten', 'Edit');
INSERT INTO `language_lib` VALUES('Bearbeitungsgeb&uuml;hr', 'Bearbeitungsgeb&uuml;hr', 'Processing fee');
INSERT INTO `language_lib` VALUES('Bearbeitungskosten', 'Bearbeitungskosten', 'Processing fees');
INSERT INTO `language_lib` VALUES('Bei Übergabe', 'Bei Übergabe', 'At handover');
INSERT INTO `language_lib` VALUES('Bei Bestätigung wird dieser Auftrag zurück auf \"Neue Bestellungen\" verwiesen', 'Bei Bestätigung wird dieser Auftrag zurück auf \"Neue Bestellungen\" verwiesen', 'Upon confirmation, this order will be referred back to \"New orders\"');
INSERT INTO `language_lib` VALUES('Bei Bestätigung wird dieser Auftrag zurück auf \"Verkaufsbereit\" verwiesen', 'Bei Bestätigung wird dieser Auftrag zurück auf \"Verkaufsbereit\" verwiesen', 'Upon confirmation, this order will be referred back to \"ready to sell\"');
INSERT INTO `language_lib` VALUES('Bei weiteren Fragen wenden Sie sich an', 'Bei weiteren Fragen wenden Sie sich an', 'If you have further questions, please contact');
INSERT INTO `language_lib` VALUES('Benötigte Artikel aus Lager entfernen<br><sub>(Standard)', 'Benötigte Artikel aus Lager entfernen<br><sub>(Standard)', 'Remove required items from warehouse<br><sub>(Default)');
INSERT INTO `language_lib` VALUES('Benötigte Artikel zum Lager hinzufügen<br><sub>(Standard)</sub>', 'Benötigte Artikel zum Lager hinzufügen<br><sub>(Standard)</sub>', 'Add required items to warehouse<br><sub>(Default)</sub>');
INSERT INTO `language_lib` VALUES('Beschreibung', 'Beschreibung', 'Description');
INSERT INTO `language_lib` VALUES('Bestand OK', 'Bestand OK', 'Stock OK');
INSERT INTO `language_lib` VALUES('Bestehend aus 2 Stiften und dazugeh&ouml;rigem Etui<br>im Wert von 24,90&euro;', 'Bestehend aus 2 Stiften und dazugeh&ouml;rigem Etui<br>im Wert von 24,90&euro;', 'Consisting of 2 pens and matching case <br> worth 24.90 &euro;');
INSERT INTO `language_lib` VALUES('Bestehend aus 2 Stiften<br>und dazugeh&ouml;rigem Etui', 'Bestehend aus 2 Stiften<br>und dazugeh&ouml;rigem Etui', 'Consisting of 2 pens<br>and matching case ');
INSERT INTO `language_lib` VALUES('Bestell-Größe', 'Bestell-Größe', 'Order-Size');
INSERT INTO `language_lib` VALUES('Bestell-Nr', 'Bestell-Nr', 'Order-Nr');
INSERT INTO `language_lib` VALUES('Bestelldaten', 'Bestelldaten', 'Order data');
INSERT INTO `language_lib` VALUES('Bestellung abschlie&szlig;en', 'Bestellung abschlie&szlig;en', 'Complete Order');
INSERT INTO `language_lib` VALUES('Bestellung abschließen', 'Bestellung abschließen', 'Complete Order');
INSERT INTO `language_lib` VALUES('Bestellung Auswählen', 'Bestellung Auswählen', 'Choose order');
INSERT INTO `language_lib` VALUES('Bestellung Nr', 'Bestellung Nr', 'Order-Nr');
INSERT INTO `language_lib` VALUES('Bestellungen', 'Bestellungen', 'Orders');
INSERT INTO `language_lib` VALUES('Bestellungen in Arbeit', 'Bestellungen in Arbeit', 'Orders in production');
INSERT INTO `language_lib` VALUES('Bestellungen Versandbereit', 'Bestellungen Versandbereit', 'Orders ready for shipping');
INSERT INTO `language_lib` VALUES('Betrag', 'Betrag', 'Sum');
INSERT INTO `language_lib` VALUES('Betrag/Prozent-Abzug (€/%)', 'Betrag/Prozent-Abzug (€/%)', 'Absolute/Percentual Discount');
INSERT INTO `language_lib` VALUES('Betreff / Titel', 'Betreff / Titel', 'Subject');
INSERT INTO `language_lib` VALUES('Bezahlt', 'Bezahlt', 'Paid');
INSERT INTO `language_lib` VALUES('Bild-Element', 'Bild-Element', 'Image-Element');
INSERT INTO `language_lib` VALUES('Bild-Element + Download', 'Bild-Element + Download', 'Image-Element + Download');
INSERT INTO `language_lib` VALUES('Bildbeschreibung', 'Bildbeschreibung', 'Image description');
INSERT INTO `language_lib` VALUES('Bitte Überweisen Sie den unten angegebenen Betrag auf das unten angegebene Konto', 'Bitte Überweisen Sie den unten angegebenen Betrag auf das unten angegebene Konto', 'Please transfer the money to the account below');
INSERT INTO `language_lib` VALUES('Blackboard', 'Blackboard', 'Blackboard');
INSERT INTO `language_lib` VALUES('Blau', 'Blau', 'blue');
INSERT INTO `language_lib` VALUES('Box', 'Box', 'Case');
INSERT INTO `language_lib` VALUES('Box einzel', 'Box einzel', 'Case single');
INSERT INTO `language_lib` VALUES('Box: Logo', 'Box: Logo', 'Case: Logo');
INSERT INTO `language_lib` VALUES('Box: Text 1', 'Box: Text 1', 'Case: Text 1');
INSERT INTO `language_lib` VALUES('Box: Text 2', 'Box: Text 2', 'Case: Text 2');
INSERT INTO `language_lib` VALUES('Breite', 'Breite', 'Width');
INSERT INTO `language_lib` VALUES('Buchhaltung', 'Buchhaltung', 'Accounting');
INSERT INTO `language_lib` VALUES('Bug Report', 'Bug Report', 'Bug report');
INSERT INTO `language_lib` VALUES('Code Löschen', 'Code Löschen', 'Delete code');
INSERT INTO `language_lib` VALUES('Datei ausw&auml;hlen', 'Datei ausw&auml;hlen', 'Choose file');
INSERT INTO `language_lib` VALUES('Datei auswählen', 'Datei auswählen', 'Choose file');
INSERT INTO `language_lib` VALUES('Datei hochladen', 'Datei hochladen', 'Upload file');
INSERT INTO `language_lib` VALUES('Datei(en) ausw&auml;hlen', 'Datei(en) ausw&auml;hlen', '');
INSERT INTO `language_lib` VALUES('Daten', 'Daten', 'Data');
INSERT INTO `language_lib` VALUES('Deine Abteilungen', 'Deine Abteilungen', 'Your departments');
INSERT INTO `language_lib` VALUES('Deine E-Mail Adresse', 'Deine E-Mail Adresse', 'Your E-Mail adresses');
INSERT INTO `language_lib` VALUES('Deine Stempelzeiten', 'Deine Stempelzeiten', 'Your timestamps');
INSERT INTO `language_lib` VALUES('Design Bearbeiten', 'Design Bearbeiten', 'Edit design');
INSERT INTO `language_lib` VALUES('Designer', 'Designer', 'Designer');
INSERT INTO `language_lib` VALUES('Deutsch', 'Deutsch', 'German');
INSERT INTO `language_lib` VALUES('Deutschland', 'Deutschland', 'Germany');
INSERT INTO `language_lib` VALUES('Die Summe der Gutscheine bel&auml;uft sich auf', 'Die Summe der Gutscheine bel&auml;uft sich auf', 'The sum of the vouchers amounts to');
INSERT INTO `language_lib` VALUES('Die Zahlung findet bei &Uuml;bergabe des Artikels statt', 'Die Zahlung findet bei &Uuml;bergabe des Artikels statt', 'The payment takes place upon delivery of the article');
INSERT INTO `language_lib` VALUES('Die Zahlung findet bei Übergabe des Artikels statt.', 'Die Zahlung findet bei Übergabe des Artikels statt.', 'The payment takes place upon delivery of the article.');
INSERT INTO `language_lib` VALUES('Dieses Element verwenden', 'Dieses Element verwenden', 'Use this element');
INSERT INTO `language_lib` VALUES('Dieses Feature wird noch nicht unterst&uuml;tzt', 'Dieses Feature wird noch nicht unterst&uuml;tzt', 'This feature is not supported yet');
INSERT INTO `language_lib` VALUES('Done', 'Done', 'Done');
INSERT INTO `language_lib` VALUES('Download', 'Download', 'Download');
INSERT INTO `language_lib` VALUES('Download Logo Box', 'Download Logo Box', 'Download Logo Case');
INSERT INTO `language_lib` VALUES('Download Logo Stift', 'Download Logo Stift', 'Download Logo Pen');
INSERT INTO `language_lib` VALUES('Druckbleistift', 'Druckbleistift', 'Pencil');
INSERT INTO `language_lib` VALUES('Druckbleistifte', 'Druckbleistifte', 'Pencils');
INSERT INTO `language_lib` VALUES('E-Mail', 'E-Mail', 'E-Mail');
INSERT INTO `language_lib` VALUES('E-Mail Link Eintragen', 'E-Mail Link Eintragen', 'Add E-Mail - Link');
INSERT INTO `language_lib` VALUES('E-Mails', 'E-Mails', 'E-Mails');
INSERT INTO `language_lib` VALUES('E-Mails an folgende Adressen werden an dich weitergeleitet', 'E-Mails an folgende Adressen werden an dich weitergeleitet', 'Emails to the following addresses will be forwarded to you');
INSERT INTO `language_lib` VALUES('Eingegangene Bestellungen', 'Eingegangene Bestellungen', 'Received orders');
INSERT INTO `language_lib` VALUES('Einkauf', 'Einkauf', 'Purchase');
INSERT INTO `language_lib` VALUES('Einstellungen', 'Einstellungen', 'Settings');
INSERT INTO `language_lib` VALUES('Eintrag Aktualisieren', 'Eintrag Aktualisieren', 'Update entry');
INSERT INTO `language_lib` VALUES('Eintrag Bearbeiten', 'Eintrag Bearbeiten', 'Edit entry');
INSERT INTO `language_lib` VALUES('Eintrag Erg&auml;nzen', 'Eintrag Erg&auml;nzen', 'Update Entry');
INSERT INTO `language_lib` VALUES('Eintrag L&ouml;schen', 'Eintrag L&ouml;schen', 'Delete entry');
INSERT INTO `language_lib` VALUES('Einzelprodukt', 'Einzelprodukt', 'Single product');
INSERT INTO `language_lib` VALUES('Element aktualisieren', 'Element aktualisieren', 'Update element');
INSERT INTO `language_lib` VALUES('Element bearbeiten', 'Element bearbeiten', 'Edit element');
INSERT INTO `language_lib` VALUES('Element hinzufügen', 'Element hinzufügen', 'Add element');
INSERT INTO `language_lib` VALUES('Email Empf&auml;nger', 'Email Empf&auml;nger', 'E-Mail Recievers');
INSERT INTO `language_lib` VALUES('Email Empfänger', 'Email Empfänger', 'E-Mail Recievers');
INSERT INTO `language_lib` VALUES('Empfänger', 'Empfänger', 'Reciever');
INSERT INTO `language_lib` VALUES('Enddatum', 'Enddatum', 'End date');
INSERT INTO `language_lib` VALUES('Englisch', 'Englisch', 'English');
INSERT INTO `language_lib` VALUES('Erhält Mails von', 'Erhält Mails von', 'Recieves mails from');
INSERT INTO `language_lib` VALUES('Etui', 'Etui', 'Case');
INSERT INTO `language_lib` VALUES('Etui gestalten', 'Etui gestalten', 'Case-Designer');
INSERT INTO `language_lib` VALUES('Fehler melden', 'Fehler melden', 'Report errors');
INSERT INTO `language_lib` VALUES('Fertigstellung', 'Fertigstellung', 'Completion');
INSERT INTO `language_lib` VALUES('Fertigung', 'Fertigung', 'Production');
INSERT INTO `language_lib` VALUES('Firma', 'Firma', 'Company');
INSERT INTO `language_lib` VALUES('Firmenname', 'Firmenname', 'Company-Name');
INSERT INTO `language_lib` VALUES('Form', 'Form', 'Shape');
INSERT INTO `language_lib` VALUES('Frau', 'Frau', 'Madam');
INSERT INTO `language_lib` VALUES('Fremde Abteilungen', 'Fremde Abteilungen', 'Other departments');
INSERT INTO `language_lib` VALUES('Fremde Stempelzeiten', 'Fremde Stempelzeiten', 'Other timestamps');
INSERT INTO `language_lib` VALUES('Fullsize Textfeld', 'Fullsize Textfeld', 'Fullsize Textfield');
INSERT INTO `language_lib` VALUES('Gegangen', 'Gegangen', 'Went');
INSERT INTO `language_lib` VALUES('Gehen', 'Gehen', 'Go');
INSERT INTO `language_lib` VALUES('Gekommen', 'Gekommen', 'Came');
INSERT INTO `language_lib` VALUES('Gekommen am', 'Gekommen am', 'Came on');
INSERT INTO `language_lib` VALUES('Generell', 'Generell', 'General');
INSERT INTO `language_lib` VALUES('Gesamt', 'Gesamt', 'Total');
INSERT INTO `language_lib` VALUES('Gewicht', 'Gewicht', 'Weight');
INSERT INTO `language_lib` VALUES('Gr&ouml;&szlig;e', 'Gr&ouml;&szlig;e', 'Size');
INSERT INTO `language_lib` VALUES('Gutschein', 'Gutschein', 'Voucher');
INSERT INTO `language_lib` VALUES('Gutschein f&uuml;r ein beliebiges Produkt kaufen', 'Gutschein f&uuml;r ein beliebiges Produkt kaufen', 'Buy voucher for any product');
INSERT INTO `language_lib` VALUES('Gutschein f&uuml;r ein WEPEN-Set', 'Gutschein f&uuml;r ein WEPEN-Set', 'Buy voucher for a WEPEN-Set');
INSERT INTO `language_lib` VALUES('Gutschein Kaufen', 'Gutschein Kaufen', 'Buy voucher');
INSERT INTO `language_lib` VALUES('Gutschein-Code', 'Gutschein-Code', 'Discount code');
INSERT INTO `language_lib` VALUES('Gutscheincode', 'Gutscheincode', 'Discount code');
INSERT INTO `language_lib` VALUES('Gutscheincode einlösen', 'Gutscheincode einlösen', 'Redeem voucher');
INSERT INTO `language_lib` VALUES('Gutscheincode Erstellen', 'Gutscheincode Erstellen', 'Create discount code');
INSERT INTO `language_lib` VALUES('Gutscheincode Hinzufügen', 'Gutscheincode Hinzufügen', 'Add discount code');
INSERT INTO `language_lib` VALUES('Gutscheine', 'Gutscheine', 'Vouchers');
INSERT INTO `language_lib` VALUES('Halbprodukt bearbeiten', 'Halbprodukt bearbeiten', '');
INSERT INTO `language_lib` VALUES('Halbprodukt l&ouml;schen', 'Halbprodukt l&ouml;schen', '');
INSERT INTO `language_lib` VALUES('Halbprodukte', 'Halbprodukte', '');
INSERT INTO `language_lib` VALUES('Halbprodukte anzeigen', 'Halbprodukte anzeigen', '');
INSERT INTO `language_lib` VALUES('Halbprodukte;semiproducts', 'Halbprodukte;semiproducts', '');
INSERT INTO `language_lib` VALUES('Herr', 'Herr', 'Sir');
INSERT INTO `language_lib` VALUES('Heutige Bestellungen', 'Heutige Bestellungen', 'Todays orders');
INSERT INTO `language_lib` VALUES('Hier Klicken um Abzustempeln', 'Hier Klicken um Abzustempeln', 'Click here to stamp out');
INSERT INTO `language_lib` VALUES('Hier Klicken um Anzustempeln', 'Hier Klicken um Anzustempeln', 'Click here to stamp in');
INSERT INTO `language_lib` VALUES('Hilfsmittel', 'Hilfsmittel', '');
INSERT INTO `language_lib` VALUES('Hilfsmittel anzeigen', 'Hilfsmittel anzeigen', '');
INSERT INTO `language_lib` VALUES('Hilfsmittel bearbeiten', 'Hilfsmittel bearbeiten', '');
INSERT INTO `language_lib` VALUES('Hilfsmittel l&ouml;schen', 'Hilfsmittel l&ouml;schen', '');
INSERT INTO `language_lib` VALUES('Hilfsmittel;support', 'Hilfsmittel;support', '');
INSERT INTO `language_lib` VALUES('Hinzufügen', 'Hinzufügen', 'Add');
INSERT INTO `language_lib` VALUES('Hochwertige, individuell gefertigte Etui<br>im Wert von 15,90&euro;', 'Hochwertige, individuell gefertigte Etui<br>im Wert von 15,90&euro;', 'High-quality, custom-made case <br> worth 15,90 &euro;');
INSERT INTO `language_lib` VALUES('Holz', 'Holz', 'Wood');
INSERT INTO `language_lib` VALUES('Ihr Logo', 'Ihr Logo', 'Your logo');
INSERT INTO `language_lib` VALUES('Ihre gew&auml;hlte Zahlungsart', 'Ihre gew&auml;hlte Zahlungsart', 'Your chosen payment method');
INSERT INTO `language_lib` VALUES('Ihre gewählte Zahlungsart', 'Ihre gewählte Zahlungsart', 'Your chosen payment method');
INSERT INTO `language_lib` VALUES('In Arbeit', 'In Arbeit', 'In progress');
INSERT INTO `language_lib` VALUES('In Kürze erhalten Sie eine E-Mail mit Zahlungsinformationen und der Auftragsbestätigung.', 'In Kürze erhalten Sie eine E-Mail mit Zahlungsinformationen und der Auftragsbestätigung.', ' You will shortly receive an e-mail with payment information and the order confirmation.');
INSERT INTO `language_lib` VALUES('In Produktion', 'In Produktion', 'In production');
INSERT INTO `language_lib` VALUES('In progress', 'In progress', 'In progress');
INSERT INTO `language_lib` VALUES('Individuell gestaltete Kugelschreiber oder Druckbleistifte<br>im Wert von 6,00&euro;', 'Individuell gestaltete Kugelschreiber oder Druckbleistifte<br>im Wert von 6,00&euro;', ' Individually designed ballpoint pens or mechanical pencils <br> worth 6.00 &euro;');
INSERT INTO `language_lib` VALUES('Info', 'Info', 'Info');
INSERT INTO `language_lib` VALUES('Inhalt', 'Inhalt', 'Content');
INSERT INTO `language_lib` VALUES('Jetzt kostenpflichtig<br>bestellen', 'Jetzt kostenpflichtig<br>bestellen', 'Order now');
INSERT INTO `language_lib` VALUES('Kommen', 'Kommen', 'Come');
INSERT INTO `language_lib` VALUES('Kommentar', 'Kommentar', 'Comment');
INSERT INTO `language_lib` VALUES('Kommentare/Hinweise für ihre Bestellung hier hinterlassen', 'Kommentare/Hinweise für ihre Bestellung hier hinterlassen', 'Leave comments / notes for your order here');
INSERT INTO `language_lib` VALUES('Konstruktion', 'Konstruktion', 'Contruction');
INSERT INTO `language_lib` VALUES('Konto', 'Konto', 'Account');
INSERT INTO `language_lib` VALUES('Kosten', 'Kosten', 'Costs');
INSERT INTO `language_lib` VALUES('Kugel', 'Kugel', 'Sphere');
INSERT INTO `language_lib` VALUES('Kugelschreiber', 'Kugelschreiber', 'Ball-Point Pen');
INSERT INTO `language_lib` VALUES('Kunde', 'Kunde', 'Customer');
INSERT INTO `language_lib` VALUES('Kunststoff', 'Kunststoff', 'Plastic');
INSERT INTO `language_lib` VALUES('Löschen', 'Löschen', 'Delete');
INSERT INTO `language_lib` VALUES('Lager', 'Lager', 'Warehouse');
INSERT INTO `language_lib` VALUES('Lagerbestand', 'Lagerbestand', 'Stock');
INSERT INTO `language_lib` VALUES('Lagerbestand Ändern', 'Lagerbestand Ändern', 'Change articles in stock');
INSERT INTO `language_lib` VALUES('Lagerbestand nicht<br>verändern', 'Lagerbestand nicht<br>verändern', 'Do not change articles in stock');
INSERT INTO `language_lib` VALUES('Land', 'Land', 'Country');
INSERT INTO `language_lib` VALUES('Letzte Arbeitszeit', 'Letzte Arbeitszeit', 'Last working-time');
INSERT INTO `language_lib` VALUES('Link Hinzufügen', 'Link Hinzufügen', 'Add Hyperlink');
INSERT INTO `language_lib` VALUES('Liter', 'Liter', 'Liters');
INSERT INTO `language_lib` VALUES('Login', 'Login', 'Login');
INSERT INTO `language_lib` VALUES('Logo', 'Logo', 'Logo');
INSERT INTO `language_lib` VALUES('Marketing', 'Marketing', 'Marketing');
INSERT INTO `language_lib` VALUES('Material', 'Material', 'Material');
INSERT INTO `language_lib` VALUES('Maximal Gewicht', 'Maximal Gewicht', 'Maximum weight');
INSERT INTO `language_lib` VALUES('Mehr', 'Mehr', 'More');
INSERT INTO `language_lib` VALUES('Melden Sie sich mit Ihrer WEPEN&reg; - E-mail Adresse an', 'Melden Sie sich mit Ihrer WEPEN&reg; - E-mail Adresse an', ' Log in with your WEPEN &reg; - E-mail address');
INSERT INTO `language_lib` VALUES('Menü', 'Menü', 'Menu');
INSERT INTO `language_lib` VALUES('Menge', 'Menge', 'Amount');
INSERT INTO `language_lib` VALUES('Mengenangabe', 'Mengenangabe', 'Quantitative disclosure');
INSERT INTO `language_lib` VALUES('Meter', 'Meter', 'Meter');
INSERT INTO `language_lib` VALUES('Methode', 'Methode', 'Method');
INSERT INTO `language_lib` VALUES('Millimeter', 'Millimeter', 'Milimeters');
INSERT INTO `language_lib` VALUES('Mindest-Bestand', 'Mindest-Bestand', 'least was');
INSERT INTO `language_lib` VALUES('Mindestbestand', 'Mindestbestand', 'least was');
INSERT INTO `language_lib` VALUES('Mit \"Bezahlt\" Markieren', 'Mit \"Bezahlt\" Markieren', 'Mark as \"Paid\"');
INSERT INTO `language_lib` VALUES('Mit \"Zahlung Ausstehend\" Markieren', 'Mit \"Zahlung Ausstehend\" Markieren', 'Mark as \"Payment pending\"');
INSERT INTO `language_lib` VALUES('Mit \"Zahlung bei Übergabe\" Markieren', 'Mit \"Zahlung bei Übergabe\" Markieren', 'Mark as \"Payment on delivery\"');
INSERT INTO `language_lib` VALUES('Mit * markierte Felder sind Pflichtfelder', 'Mit * markierte Felder sind Pflichtfelder', 'Fields marked with * have to be filled');
INSERT INTO `language_lib` VALUES('N&auml;chster Schritt', 'N&auml;chster Schritt', 'Next step');
INSERT INTO `language_lib` VALUES('Nach Bestell-Nr. Suchen', 'Nach Bestell-Nr. Suchen', 'Search for Order-Nr.');
INSERT INTO `language_lib` VALUES('Nach Bestell-Nr. Suchen...', 'Nach Bestell-Nr. Suchen...', 'Search for Order-Nr. ...');
INSERT INTO `language_lib` VALUES('Nachbestellen!', 'Nachbestellen!', 'Reorder!');
INSERT INTO `language_lib` VALUES('Nachname', 'Nachname', 'Last name');
INSERT INTO `language_lib` VALUES('Name', 'Name', 'Name');
INSERT INTO `language_lib` VALUES('Neue Bestellungen', 'Neue Bestellungen', 'New orders');
INSERT INTO `language_lib` VALUES('Neue Sektion hinzufügen', 'Neue Sektion hinzufügen', 'Add new section');
INSERT INTO `language_lib` VALUES('Neue Task hinzuf&uuml;gen', 'Neue Task hinzuf&uuml;gen', 'Add new Task');
INSERT INTO `language_lib` VALUES('Neue Versandart', 'Neue Versandart', 'New shippment type');
INSERT INTO `language_lib` VALUES('Neue Versandart hinzufügen', 'Neue Versandart hinzufügen', 'Add new shippment type');
INSERT INTO `language_lib` VALUES('Neue Ware Anlegen', 'Neue Ware Anlegen', 'Add new item');
INSERT INTO `language_lib` VALUES('Neue Ware im Sortiment aufnehmen', 'Neue Ware im Sortiment aufnehmen', 'Add new item to range');
INSERT INTO `language_lib` VALUES('Neues Element hinzufügen', 'Neues Element hinzufügen', 'Add new element');
INSERT INTO `language_lib` VALUES('Neues Halbprodukt eintragen', 'Neues Halbprodukt eintragen', '');
INSERT INTO `language_lib` VALUES('Neues Hilfsmittel eintragen', 'Neues Hilfsmittel eintragen', '');
INSERT INTO `language_lib` VALUES('Neues Passwort', 'Neues Passwort', 'New password');
INSERT INTO `language_lib` VALUES('Neues Produkt Anlegen', 'Neues Produkt Anlegen', 'Add new product');
INSERT INTO `language_lib` VALUES('Neues Produkt eintragen', 'Neues Produkt eintragen', '');
INSERT INTO `language_lib` VALUES('Neues Rohteil eintragen', 'Neues Rohteil eintragen', '');
INSERT INTO `language_lib` VALUES('Neuigkeiten in dieser Abteilung', 'Neuigkeiten in dieser Abteilung', 'News in this department');
INSERT INTO `language_lib` VALUES('Nicht angestempelt', 'Nicht angestempelt', 'Not stamped');
INSERT INTO `language_lib` VALUES('Nr.', 'Nr.', 'Nr.');
INSERT INTO `language_lib` VALUES('Nutzer', 'Nutzer', 'User');
INSERT INTO `language_lib` VALUES('Nutzer Eintragen', 'Nutzer Eintragen', 'Add user');
INSERT INTO `language_lib` VALUES('Nutzer Hinzuf&uuml;gen', 'Nutzer Hinzuf&uuml;gen', 'Add user');
INSERT INTO `language_lib` VALUES('Nutzer Registrieren', 'Nutzer Registrieren', 'Register User');
INSERT INTO `language_lib` VALUES('oder w&auml;hlen Sie das zu bearbeitende Element hier aus', 'oder w&auml;hlen Sie das zu bearbeitende Element hier aus', ' or select the item to edit here');
INSERT INTO `language_lib` VALUES('oder w&auml;hlen Sie das zu bearbeitende Element hier aus:', 'oder w&auml;hlen Sie das zu bearbeitende Element hier aus:', ' or select the item to edit here:');
INSERT INTO `language_lib` VALUES('Online', 'Online', 'Online');
INSERT INTO `language_lib` VALUES('Operationen', 'Operationen', 'Operations');
INSERT INTO `language_lib` VALUES('Opertationen', 'Operationen', 'Operations');
INSERT INTO `language_lib` VALUES('Option', 'Option', 'Option');
INSERT INTO `language_lib` VALUES('Ort', 'Ort', 'City');
INSERT INTO `language_lib` VALUES('Passwort', 'Passwort', 'Password');
INSERT INTO `language_lib` VALUES('Passwort ändern', 'Passwort ändern', 'Change password');
INSERT INTO `language_lib` VALUES('Passwort Wiederholen', 'Passwort Wiederholen', 'Confirm password');
INSERT INTO `language_lib` VALUES('PayPal - in K&uuml;rze', 'PayPal - in K&uuml;rze', 'PayPal - comming soon');
INSERT INTO `language_lib` VALUES('PayPal - in Kürze', 'PayPal - in Kürze', 'PayPal - comming soon');
INSERT INTO `language_lib` VALUES('PayPal - in K�rze', 'PayPal - in K�rze', 'PayPal - comming soon');
INSERT INTO `language_lib` VALUES('Personal', 'Personal', 'Personal');
INSERT INTO `language_lib` VALUES('PLZ', 'PLZ', 'ZIP-Code');
INSERT INTO `language_lib` VALUES('PLZ / Ort', 'PLZ / Ort', 'ZIP-Code / City');
INSERT INTO `language_lib` VALUES('PLZ/Ort', 'PLZ/Ort', 'ZIP Code / City');
INSERT INTO `language_lib` VALUES('Postfächer', 'Postfächer', 'Inboxes');
INSERT INTO `language_lib` VALUES('Preis', 'Preis', 'Price');
INSERT INTO `language_lib` VALUES('Preisnachlass', 'Preisnachlass', 'Discount');
INSERT INTO `language_lib` VALUES('Preisstaffelung', 'Preisstaffelung', 'Price-graduation');
INSERT INTO `language_lib` VALUES('Produkt', 'Produkt', 'Product');
INSERT INTO `language_lib` VALUES('Produkt bearbeiten', 'Produkt bearbeiten', 'Edit product');
INSERT INTO `language_lib` VALUES('Produkt Bestandteile', 'Produkt Bestandteile', 'Product components');
INSERT INTO `language_lib` VALUES('Produkt Bezahlt', 'Produkt Bezahlt', 'Product paid');
INSERT INTO `language_lib` VALUES('Produkt Fertigstellen', 'Produkt Fertigstellen', 'Finish product');
INSERT INTO `language_lib` VALUES('Produkt im Katalog aufnehmen', 'Produkt im Katalog aufnehmen', 'Add product to catalog');
INSERT INTO `language_lib` VALUES('Produkt l&ouml', 'Produkt l&ouml', '');
INSERT INTO `language_lib` VALUES('Produkt l&ouml;schen', 'Produkt l&ouml;schen', '');
INSERT INTO `language_lib` VALUES('Produkt löschen', 'Produkt löschen', 'Delete product');
INSERT INTO `language_lib` VALUES('Produkt l�schen', 'Produkt l�schen', '');
INSERT INTO `language_lib` VALUES('Produkt-Übersicht', 'Produkt-Übersicht', 'Product-overview');
INSERT INTO `language_lib` VALUES('Produkt-Bezeichnung', 'Produkt-Bezeichnung', 'Product-description');
INSERT INTO `language_lib` VALUES('Produkt-Name', 'Produkt-Name', 'Product-name');
INSERT INTO `language_lib` VALUES('Produkt-Nummer', 'Produkt-Nummer', 'Product-number');
INSERT INTO `language_lib` VALUES('Produkte', 'Produkte', 'Products');
INSERT INTO `language_lib` VALUES('Produkte anzeigen', 'Produkte anzeigen', '');
INSERT INTO `language_lib` VALUES('Produkte gesammt', 'Produkte gesammt', 'Products total');
INSERT INTO `language_lib` VALUES('Produkte verwalten', 'Produkte verwalten', 'Manage products');
INSERT INTO `language_lib` VALUES('Produkte;products', 'Produkte;products', '');
INSERT INTO `language_lib` VALUES('Produkte|!|products', 'Produkte|!|products', '');
INSERT INTO `language_lib` VALUES('Produktion', 'Produktion', 'Production');
INSERT INTO `language_lib` VALUES('Produktion abbrechen', 'Produktion abbrechen', 'Cancel production');
INSERT INTO `language_lib` VALUES('Produktion abschließen', 'Produktion abschließen', 'Finish production');
INSERT INTO `language_lib` VALUES('Produktion Starten', 'Produktion Starten', 'Start production');
INSERT INTO `language_lib` VALUES('Produktion zurücksetzen', 'Produktion zurücksetzen', 'Reset production');
INSERT INTO `language_lib` VALUES('Produktions-Status', 'Produktions-Status', 'Production status');
INSERT INTO `language_lib` VALUES('Produktionsdaten', 'Produktionsdaten', 'Production data');
INSERT INTO `language_lib` VALUES('Produktvorschau', 'Produktvorschau', 'Product preview');
INSERT INTO `language_lib` VALUES('Produktwahl', 'Produktwahl', 'Choose Products');
INSERT INTO `language_lib` VALUES('Protokoll', 'Protokoll', 'Protocoll');
INSERT INTO `language_lib` VALUES('Prozentual', 'Prozentual', 'Percentual');
INSERT INTO `language_lib` VALUES('Quader', 'Quader', 'Cublicle');
INSERT INTO `language_lib` VALUES('Rabatt Nachtragen', 'Rabatt Nachtragen', 'Add Discount');
INSERT INTO `language_lib` VALUES('Rabatte', 'Rabatte', 'Discounts');
INSERT INTO `language_lib` VALUES('Rechnung', 'Rechnung', 'Bill');
INSERT INTO `language_lib` VALUES('Rechnung ausschreiben', 'Rechnung ausschreiben', 'Send Bill');
INSERT INTO `language_lib` VALUES('Rechnung erstellen', 'Rechnung erstellen', 'Create Bill');
INSERT INTO `language_lib` VALUES('Rechnung erzeugen', 'Rechnung erzeugen', 'Generate bill');
INSERT INTO `language_lib` VALUES('Rechnung Nr', 'Rechnung Nr', 'Bill-Nr');
INSERT INTO `language_lib` VALUES('Rechnungen', 'Rechnungen', 'Bills');
INSERT INTO `language_lib` VALUES('Reduzierung', 'Reduzierung', 'Reduction');
INSERT INTO `language_lib` VALUES('Registrierte Adressen', 'Registrierte Adressen', 'Registrated adresses');
INSERT INTO `language_lib` VALUES('Restliche Nutzungen', 'Restliche Nutzungen', 'Uses left');
INSERT INTO `language_lib` VALUES('Rohteil bearbeiten', 'Rohteil bearbeiten', '');
INSERT INTO `language_lib` VALUES('Rohteil l&ouml;schen', 'Rohteil l&ouml;schen', '');
INSERT INTO `language_lib` VALUES('Rohteile', 'Rohteile', '');
INSERT INTO `language_lib` VALUES('Rohteile anzeigen', 'Rohteile anzeigen', '');
INSERT INTO `language_lib` VALUES('Rohteile;raw', 'Rohteile;raw', '');
INSERT INTO `language_lib` VALUES('Rot', 'Rot', 'red');
INSERT INTO `language_lib` VALUES('Rotation', 'Rotation', 'rotation');
INSERT INTO `language_lib` VALUES('Schriftart', 'Schriftart', 'Font type');
INSERT INTO `language_lib` VALUES('Schweiz', 'Schweiz', 'Swiss');
INSERT INTO `language_lib` VALUES('SCRUM', 'SCRUM', 'SCRUM');
INSERT INTO `language_lib` VALUES('SCRUM - Blackboard', 'SCRUM - Blackboard', 'SCRUM-Blackboard');
INSERT INTO `language_lib` VALUES('SCRUM - Einstellungen', 'SCRUM - Einstellungen', 'SCRUM-Settings');
INSERT INTO `language_lib` VALUES('SCRUM-Settings', 'SCRUM-Settings', 'SCRUM-Settings');
INSERT INTO `language_lib` VALUES('Sektion Hinzufügen', 'Sektion Hinzufügen', 'Add section');
INSERT INTO `language_lib` VALUES('Sektion löschen', 'Sektion löschen', 'Delete section');
INSERT INTO `language_lib` VALUES('Sektions-Name', 'Sektions-Name', 'Section-name');
INSERT INTO `language_lib` VALUES('Selbstabholung', 'Selbstabholung', 'Pickup');
INSERT INTO `language_lib` VALUES('Service', 'Service', 'Service');
INSERT INTO `language_lib` VALUES('Set gestalten', 'Set gestalten', 'Set-Designer');
INSERT INTO `language_lib` VALUES('Set w&auml;hlen', 'Set w&auml;hlen', 'Choose set');
INSERT INTO `language_lib` VALUES('SharePoint', 'SharePoint', 'SharePoint');
INSERT INTO `language_lib` VALUES('Sicherheit', 'Sicherheit', 'Security');
INSERT INTO `language_lib` VALUES('Sie werden informiert sobald Ihre Zahlung eingegangen ist.', 'Sie werden informiert sobald Ihre Zahlung eingegangen ist.', ' You will be informed as soon as your payment has been received.');
INSERT INTO `language_lib` VALUES('Sie werden rechtzeitig über den Auslieferungstermin per E-Mail benachrichtigt.', 'Sie werden rechtzeitig über den Auslieferungstermin per E-Mail benachrichtigt.', ' You will be notified in time about the delivery date by e-mail.');
INSERT INTO `language_lib` VALUES('Sonstiges', 'Sonstiges', 'Other');
INSERT INTO `language_lib` VALUES('Special Erstellen', 'Special Erstellen', 'Create Special');
INSERT INTO `language_lib` VALUES('Special Hinzufügen', 'Special Hinzufügen', 'Add Special');
INSERT INTO `language_lib` VALUES('Special-Name', 'Special-Name', 'Special-name');
INSERT INTO `language_lib` VALUES('St&uuml;ckpreis', 'St&uuml;ckpreis', 'Price per piece');
INSERT INTO `language_lib` VALUES('St&uuml;ckzahlen', 'St&uuml;ckzahlen', 'Number of pieces');
INSERT INTO `language_lib` VALUES('Stück', 'Stück', 'Pieces');
INSERT INTO `language_lib` VALUES('Stückbegrenzung', 'Stückbegrenzung', 'Limit of pieces');
INSERT INTO `language_lib` VALUES('Stückpreis', 'Stückpreis', 'Price per piece');
INSERT INTO `language_lib` VALUES('Stückzahl', 'Stückzahl', 'Number of pieces');
INSERT INTO `language_lib` VALUES('Staffelung', 'Staffelung', 'Graduation');
INSERT INTO `language_lib` VALUES('Staffelung Bearbeiten', 'Staffelung Bearbeiten', 'Edit graduation');
INSERT INTO `language_lib` VALUES('Stahl', 'Stahl', 'Steel');
INSERT INTO `language_lib` VALUES('Standart-Set', 'Standart-Set', 'Default-Set');
INSERT INTO `language_lib` VALUES('Standartsprache f&uuml;r Designer', 'Standartsprache f&uuml;r Designer', 'Default language for Designer');
INSERT INTO `language_lib` VALUES('Standartsprache f&uuml;r ERP', 'Standartsprache f&uuml;r ERP', 'Default language for ERP');
INSERT INTO `language_lib` VALUES('Startdatum', 'Startdatum', 'Start date');
INSERT INTO `language_lib` VALUES('Statistik', 'Statistik', 'Statistics');
INSERT INTO `language_lib` VALUES('Status', 'Status', 'Status');
INSERT INTO `language_lib` VALUES('Stift einzel', 'Stift einzel', 'Pen single');
INSERT INTO `language_lib` VALUES('Stift: Logo', 'Stift: Logo', 'Pen: Logo');
INSERT INTO `language_lib` VALUES('Stift: Text', 'Stift: Text', 'Pen: Text');
INSERT INTO `language_lib` VALUES('Stifte gestalten', 'Stifte gestalten', 'Pen-Designer');
INSERT INTO `language_lib` VALUES('Stk', 'Stk', 'Pcs');
INSERT INTO `language_lib` VALUES('Story-Points', 'Story-Points', 'Storypoints');
INSERT INTO `language_lib` VALUES('Storypoints &auml;ndern', 'Storypoints &auml;ndern', 'Change Storypoints');
INSERT INTO `language_lib` VALUES('Storypoints Aktualisieren', 'Storypoints Aktualisieren', 'Update Storypoints');
INSERT INTO `language_lib` VALUES('Stra&szlig;e', 'Stra&szlig;e', 'Street');
INSERT INTO `language_lib` VALUES('Stra&szlig;e / Hausnummer', 'Stra&szlig;e / Hausnummer', 'Street / Nr.');
INSERT INTO `language_lib` VALUES('Straße', 'Straße', 'Street');
INSERT INTO `language_lib` VALUES('Straße / Hausnummer', 'Straße / Hausnummer', 'Street / Nr.');
INSERT INTO `language_lib` VALUES('Straße/Nr', 'Straße/Nr', 'Street Nr');
INSERT INTO `language_lib` VALUES('Suchen', 'Suchen', 'Search');
INSERT INTO `language_lib` VALUES('System', 'System', 'System');
INSERT INTO `language_lib` VALUES('Task beanspruchen', 'Task beanspruchen', 'Claim Task');
INSERT INTO `language_lib` VALUES('Task hinzuf&uuml;gen', 'Task hinzuf&uuml;gen', 'Add Task');
INSERT INTO `language_lib` VALUES('Text', 'Text', 'Text');
INSERT INTO `language_lib` VALUES('Text 1', 'Text 1', 'Text 1');
INSERT INTO `language_lib` VALUES('Text 2', 'Text 2', 'Text 2');
INSERT INTO `language_lib` VALUES('Text-Element', 'Text-Element', 'Text element');
INSERT INTO `language_lib` VALUES('Text-Elemente', 'Text-Elemente', 'Text elements');
INSERT INTO `language_lib` VALUES('Textausrichtung', 'Textausrichtung', 'Text alignment');
INSERT INTO `language_lib` VALUES('Textgr&ouml;&szlig;e', 'Textgr&ouml;&szlig;e', 'Font size');
INSERT INTO `language_lib` VALUES('Textgr&ouml&szlig;e', 'Textgr&ouml&szlig;e', 'Font size');
INSERT INTO `language_lib` VALUES('Textgröße', 'Textgröße', 'Font size');
INSERT INTO `language_lib` VALUES('Titel', 'Titel', 'Title');
INSERT INTO `language_lib` VALUES('To be validated', 'To be validated', 'To be validated');
INSERT INTO `language_lib` VALUES('�berweisung', '�berweisung', 'Transfer');
INSERT INTO `language_lib` VALUES('Unbegonnen', 'Unbegonnen', 'Unstarted');
INSERT INTO `language_lib` VALUES('Unbegonnene', 'Unbegonnene', 'Unstarted');
INSERT INTO `language_lib` VALUES('Unlimitierte Verwendungen', 'Unlimitierte Verwendungen', 'Unlimited uses');
INSERT INTO `language_lib` VALUES('Unstarted', 'Unstarted', 'Unstarted');
INSERT INTO `language_lib` VALUES('Unwiderruflich Löschen', 'Unwiderruflich Löschen', 'Delete');
INSERT INTO `language_lib` VALUES('Update', 'Update', 'Update');
INSERT INTO `language_lib` VALUES('Verkauf', 'Verkauf', 'Sale');
INSERT INTO `language_lib` VALUES('Verkaufsbereit', 'Verkaufsbereit', 'Ready for selling');
INSERT INTO `language_lib` VALUES('Verkauft', 'Verkauft', 'Sold');
INSERT INTO `language_lib` VALUES('Verkaufte Artikel', 'Verkaufte Artikel', 'Sold Pieces');
INSERT INTO `language_lib` VALUES('Versand', 'Versand', 'Shipping');
INSERT INTO `language_lib` VALUES('Versand anrechnen', 'Versand anrechnen', 'Add Shipping Costs');
INSERT INTO `language_lib` VALUES('Versand verwalten', 'Versand verwalten', 'Manage Shipping');
INSERT INTO `language_lib` VALUES('Versandart', 'Versandart', 'Delivery');
INSERT INTO `language_lib` VALUES('Versandart löschen', 'Versandart löschen', 'Delete Shippment Type');
INSERT INTO `language_lib` VALUES('Versandarten', 'Versandarten', 'Shippment Types');
INSERT INTO `language_lib` VALUES('Versandkosten Standart', 'Versandkosten Standart', 'Shipping costs standard');
INSERT INTO `language_lib` VALUES('Versandstyp hinzufügen', 'Versandstyp hinzufügen', 'Add Shippment-Type');
INSERT INTO `language_lib` VALUES('Versandstyp L&ouml;schen', 'Versandstyp L&ouml;schen', 'Delete Shippment-Type');
INSERT INTO `language_lib` VALUES('Vertritt Abteilung', 'Vertritt Abteilung', 'Represents');
INSERT INTO `language_lib` VALUES('Verwaltung', 'Verwaltung', 'Management');
INSERT INTO `language_lib` VALUES('Verwendungszweck', 'Verwendungszweck', 'Usage');
INSERT INTO `language_lib` VALUES('Vielen Dank f&uuml;r ihre Bestellung!', 'Vielen Dank f&uuml;r ihre Bestellung!', 'Thank you for your order!');
INSERT INTO `language_lib` VALUES('Vielen Dank für ihre Bestellung!', 'Vielen Dank für ihre Bestellung!', 'Thank you for your order!');
INSERT INTO `language_lib` VALUES('Von', 'Von', 'From');
INSERT INTO `language_lib` VALUES('von-bis', 'von-bis', 'from-to');
INSERT INTO `language_lib` VALUES('Vorhandene Ware aus Sortiment entfernen', 'Vorhandene Ware aus Sortiment entfernen', 'Remove items from warehouse');
INSERT INTO `language_lib` VALUES('Vorhandene Ware L&ouml;schen', 'Vorhandene Ware L&ouml;schen', 'Delete existing item');
INSERT INTO `language_lib` VALUES('Vorhandenes Produkt L&ouml;schen', 'Vorhandenes Produkt L&ouml;schen', 'Delete existing product');
INSERT INTO `language_lib` VALUES('Vorheriger Schritt', 'Vorheriger Schritt', 'Previous step');
INSERT INTO `language_lib` VALUES('Vorname', 'Vorname', 'First Name');
INSERT INTO `language_lib` VALUES('Vorschläge / Anforderungen', 'Vorschläge / Anforderungen', 'Requests');
INSERT INTO `language_lib` VALUES('W&auml;hlen Sie den gew&uuml;nschten Artikel aus', 'W&auml;hlen Sie den gew&uuml;nschten Artikel aus', 'Select your desired article');
INSERT INTO `language_lib` VALUES('W&auml;hlen Sie die Stifte aus die in ihrem WEPEN-Etui enthalten sein sollten', 'W&auml;hlen Sie die Stifte aus die in ihrem WEPEN-Etui enthalten sein sollten', ' Select the pens that should be included in your WEPEN case');
INSERT INTO `language_lib` VALUES('W&auml;hlen Sie ein Objekt aus um seine Eigenschaften zu &auml;ndern', 'W&auml;hlen Sie ein Objekt aus um seine Eigenschaften zu &auml;ndern', 'Select an object to change its properties');
INSERT INTO `language_lib` VALUES('Würfel', 'Würfel', 'Cube');
INSERT INTO `language_lib` VALUES('Ware zum Angebot Hinzufügen', 'Ware zum Angebot Hinzufügen', 'Add item to offer');
INSERT INTO `language_lib` VALUES('Waren nachtragen', 'Waren nachtragen', 'Add Item');
INSERT INTO `language_lib` VALUES('Warenaufteilung', 'Warenaufteilung', 'Item division');
INSERT INTO `language_lib` VALUES('Warenstruktur', 'Warenstruktur', 'Warestructure');
INSERT INTO `language_lib` VALUES('Warenstruktur (Strukturbaum)', 'Warenstruktur (Strukturbaum)', 'Warestructure (Tree)');
INSERT INTO `language_lib` VALUES('Websites', 'Websites', 'Websites');
INSERT INTO `language_lib` VALUES('Weitere Bestellung aufgeben', 'Weitere Bestellung aufgeben', 'Place another order');
INSERT INTO `language_lib` VALUES('WEPEN-Etui', 'WEPEN-Etui', 'WEPEN-Case');
INSERT INTO `language_lib` VALUES('WEPEN-Set', 'WEPEN-Set', 'WEPEN-Set');
INSERT INTO `language_lib` VALUES('WEPEN-Set Gutschein kaufen', 'WEPEN-Set Gutschein kaufen', 'Buy WEPEN-Vouchers');
INSERT INTO `language_lib` VALUES('WEPEN-Stifte', 'WEPEN-Stifte', 'WEPEN-Pens');
INSERT INTO `language_lib` VALUES('Wilkommen zur&uuml;ck', 'Wilkommen zur&uuml;ck', 'Welcome back');
INSERT INTO `language_lib` VALUES('Zahlung', 'Zahlung', 'Payment');
INSERT INTO `language_lib` VALUES('Zahlung ausstehend', 'Zahlung ausstehend', 'Payment pending');
INSERT INTO `language_lib` VALUES('Zahlung bei Übergabe', 'Zahlung bei Übergabe', 'Payment on delivery');
INSERT INTO `language_lib` VALUES('Zahlung bei �bergabe', 'Zahlung bei �bergabe', '');
INSERT INTO `language_lib` VALUES('Zahlung eingegangen', 'Zahlung eingegangen', 'Payment Recieved');
INSERT INTO `language_lib` VALUES('Zahlungs-Status', 'Zahlungs-Status', 'Payment Status');
INSERT INTO `language_lib` VALUES('Zahlungs-Status ändern', 'Zahlungs-Status ändern', 'Change Payment Status');
INSERT INTO `language_lib` VALUES('Zahlungsmethode', 'Zahlungsmethode', 'Payment method');
INSERT INTO `language_lib` VALUES('Zahlungsstatus ändern', 'Zahlungsstatus ändern', 'Change Payment Status');
INSERT INTO `language_lib` VALUES('Zeit gearbeitet', 'Zeit gearbeitet', 'Time worked');
INSERT INTO `language_lib` VALUES('Zeit Nachtragen', 'Zeit Nachtragen', 'Add Timestamp');
INSERT INTO `language_lib` VALUES('Zeiterfassung', 'Zeiterfassung', 'Timestamp');
INSERT INTO `language_lib` VALUES('Zeitkorrektur', 'Zeitkorrektur', 'Timecorrection');
INSERT INTO `language_lib` VALUES('Zeitraum', 'Zeitraum', 'Timespan');
INSERT INTO `language_lib` VALUES('Zentimeter', 'Zentimeter', 'Centimeters');
INSERT INTO `language_lib` VALUES('Zu deinem E-Mail Postfach', 'Zu deinem E-Mail Postfach', 'To your Inbox');
INSERT INTO `language_lib` VALUES('zu je', 'zu je', 'for');
INSERT INTO `language_lib` VALUES('Zuletzt gegangen am', 'Zuletzt gegangen am', 'Last left on');
INSERT INTO `language_lib` VALUES('Zum Designer Wechseln', 'Zum Designer Wechseln', 'Switch to Designer');
INSERT INTO `language_lib` VALUES('Zur zahlung', 'Zur zahlung', 'Continue to payment');
INSERT INTO `language_lib` VALUES('Zur&uuml;ck zur WEPEN-Homepage', 'Zur&uuml;ck zur WEPEN-Homepage', ' Back to the WEPEN homepage');
INSERT INTO `language_lib` VALUES('Zurück zur WEPEN-Homepage', 'Zurück zur WEPEN-Homepage', ' Back to the WEPEN homepage');
INSERT INTO `language_lib` VALUES('Zurücksetzen', 'Zurücksetzen', 'Reset');
INSERT INTO `language_lib` VALUES('Zusammenstellung', 'Zusammenstellung', 'Compilation');
INSERT INTO `language_lib` VALUES('Zuständig', 'Zuständig', 'Responsible');
INSERT INTO `language_lib` VALUES('Zuweisung Hinzufügen', 'Zuweisung Hinzufügen', 'Add Assigment');
INSERT INTO `language_lib` VALUES('Zylinder', 'Zylinder', 'Cylinder');
CREATE TABLE `product_contains` (  `id` varchar(13) COLLATE utf8_unicode_ci NOT NULL,  `parent` varchar(50) COLLATE utf8_unicode_ci NOT NULL,  `child` varchar(50) COLLATE utf8_unicode_ci NOT NULL,  `quantity` float NOT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
INSERT INTO `product_contains` VALUES('5ac2a43758490', 'HLSP-MC32', 'HLRW-1508', '1');
INSERT INTO `product_contains` VALUES('5ac2a4375b293', 'HLSP-MC32', 'HLRW-1514', '1');
INSERT INTO `product_contains` VALUES('5ac2a4375e0b2', 'HLSP-MC32', 'HLRW-2503', '2');
INSERT INTO `product_contains` VALUES('5ac2a43760f2a', 'HLSP-MC32', 'HLRW-2510', '2');
INSERT INTO `product_contains` VALUES('5ac2a43763bb3', 'HLSP-MC32', 'HLRW-3222', '2');
INSERT INTO `product_contains` VALUES('5ac2a437667cc', 'HLSP-MC32', 'HLRW-3368', '5');
INSERT INTO `product_contains` VALUES('5ac2a437694ba', 'HLSP-MC32', 'HLRW-4025', '5');
INSERT INTO `product_contains` VALUES('5ac2a4376c1a9', 'HLSP-MC32', 'HLRW-8104', '1');
INSERT INTO `product_contains` VALUES('5ac2a4376edce', 'HLSP-MC32', 'HLRW-8213', '1');
INSERT INTO `product_contains` VALUES('5ac2a43771b70', 'HLSP-MC32', 'HLRW-9132', '1');
INSERT INTO `product_contains` VALUES('5ac2a43772267', 'HLSP-MC32', 'HLRW-9236', '1');
INSERT INTO `product_contains` VALUES('5ac2a4377295e', 'HLSP-MC32', 'HLRW-9320', '1');
INSERT INTO `product_contains` VALUES('5ac2a437756d4', 'HLSP-MC32', 'HLRW-9323', '1');
INSERT INTO `product_contains` VALUES('5ac2a43778596', 'HLSP-MC32', 'HLRW-9328', '1');
INSERT INTO `product_contains` VALUES('5ac2a4377b904', 'HLSP-MC32', 'HLSU-1010', '1');
INSERT INTO `product_contains` VALUES('5ac2a4a4ecc86', 'HLSP-SC42', 'HLRW-1514', '1');
INSERT INTO `product_contains` VALUES('5ac2a4a4efb1e', 'HLSP-SC42', 'HLRW-2503', '5');
INSERT INTO `product_contains` VALUES('5ac2a4a4f021a', 'HLSP-SC42', 'HLRW-2510', '3');
INSERT INTO `product_contains` VALUES('5ac2a4a4f09f0', 'HLSP-SC42', 'HLRW-3220', '6');
INSERT INTO `product_contains` VALUES('5ac2a4a4f395e', 'HLSP-SC42', 'HLRW-3222', '5');
INSERT INTO `product_contains` VALUES('5ac2a4a502633', 'HLSP-SC42', 'HLRW-3368', '8');
INSERT INTO `product_contains` VALUES('5ac2a4a505575', 'HLSP-SC42', 'HLRW-4025', '8');
INSERT INTO `product_contains` VALUES('5ac2a4a5081e9', 'HLSP-SC42', 'HLRW-5123', '6');
INSERT INTO `product_contains` VALUES('5ac2a4a50b070', 'HLSP-SC42', 'HLRW-8104', '1');
INSERT INTO `product_contains` VALUES('5ac2a4a50b6ed', 'HLSP-SC42', 'HLRW-9328', '1');
INSERT INTO `product_contains` VALUES('5ac2a4a50e3cb', 'HLSP-SC42', 'HLRW-9403', '1');
INSERT INTO `product_contains` VALUES('5ac2a4a513cce', 'HLSP-SC42', 'HLSU-1010', '1');
INSERT INTO `product_contains` VALUES('5ac2a564b58a1', 'HLSP-SO10', 'HLRW-1315', '2');
INSERT INTO `product_contains` VALUES('5ac2a564b862e', 'HLSP-SO10', 'HLRW-1514', '2');
INSERT INTO `product_contains` VALUES('5ac2a564bb5be', 'HLSP-SO10', 'HLRW-2503', '4');
INSERT INTO `product_contains` VALUES('5ac2a564be2a3', 'HLSP-SO10', 'HLRW-2510', '3');
INSERT INTO `product_contains` VALUES('5ac2a564be8aa', 'HLSP-SO10', 'HLRW-3210', '2');
INSERT INTO `product_contains` VALUES('5ac2a564c1379', 'HLSP-SO10', 'HLRW-3222', '4');
INSERT INTO `product_contains` VALUES('5ac2a564c3f11', 'HLSP-SO10', 'HLRW-3291', '2');
INSERT INTO `product_contains` VALUES('5ac2a564c6bb7', 'HLSP-SO10', 'HLRW-3310', '2');
INSERT INTO `product_contains` VALUES('5ac2a564c9964', 'HLSP-SO10', 'HLRW-3368', '6');
INSERT INTO `product_contains` VALUES('5ac2a564cc627', 'HLSP-SO10', 'HLRW-4025', '6');
INSERT INTO `product_contains` VALUES('5ac2a564cf177', 'HLSP-SO10', 'HLRW-6105', '2');
INSERT INTO `product_contains` VALUES('5ac2a564d1c52', 'HLSP-SO10', 'HLRW-7158', '3');
INSERT INTO `product_contains` VALUES('5ac2a564d47a9', 'HLSP-SO10', 'HLRW-8104', '1');
INSERT INTO `product_contains` VALUES('5ac2a564d7585', 'HLSP-SO10', 'HLRW-8332', '1');
INSERT INTO `product_contains` VALUES('5ac2a564da377', 'HLSP-SO10', 'HLRW-9328', '1');
INSERT INTO `product_contains` VALUES('5ac2a564dff43', 'HLSP-SO10', 'HLSU-1010', '1');
INSERT INTO `product_contains` VALUES('5ac2a5a2d4247', 'HLSP-PB10', 'HLRW-7140', '4');
INSERT INTO `product_contains` VALUES('5ac2a5a2d6fec', 'HLSP-PB10', 'HLRW-9259', '1');
INSERT INTO `product_contains` VALUES('5ac2a5a2d9c22', 'HLSP-PB10', 'HLRW-9812', '1');
INSERT INTO `product_contains` VALUES('5ac2a5a2dcc61', 'HLSP-PB10', 'HLSU-1010', '1');
INSERT INTO `product_contains` VALUES('5ac2a65dbe4c5', 'HLSP-AF10', 'HLRW-1518', '2');
INSERT INTO `product_contains` VALUES('5ac2a65dc119d', 'HLSP-AF10', 'HLRW-2110', '2');
INSERT INTO `product_contains` VALUES('5ac2a65dc4069', 'HLSP-AF10', 'HLRW-3212', '2');
INSERT INTO `product_contains` VALUES('5ac2a65dc6f42', 'HLSP-AF10', 'HLRW-3238', '2');
INSERT INTO `product_contains` VALUES('5ac2a65dc757e', 'HLSP-AF10', 'HLRW-3710', '1');
INSERT INTO `product_contains` VALUES('5ac2a65dc7b99', 'HLSP-AF10', 'HLRW-3810', '3');
INSERT INTO `product_contains` VALUES('5ac2a65dca9c2', 'HLSP-AF10', 'HLRW-6222', '2');
INSERT INTO `product_contains` VALUES('5ac2a65dcd5cc', 'HLSP-AF10', 'HLRW-8339', '2');
INSERT INTO `product_contains` VALUES('5ac2a6b988246', 'HLSP-FP10', 'HLRW-2510', '2');
INSERT INTO `product_contains` VALUES('5ac2a6b98b23c', 'HLSP-FP10', 'HLRW-3810', '1');
INSERT INTO `product_contains` VALUES('5ac2a6b98dd55', 'HLSP-FP10', 'HLRW-9122', '5');
INSERT INTO `product_contains` VALUES('5ac2a6b990887', 'HLSP-FP10', 'HLRW-9146', '1');
INSERT INTO `product_contains` VALUES('5ac2a6b990f62', 'HLSP-FP10', 'HLRW-9306', '1');
INSERT INTO `product_contains` VALUES('5ac2a6b991414', 'HLSP-FP10', 'HLRW-9602', '1');
INSERT INTO `product_contains` VALUES('5ac2a6b99459f', 'HLSP-FP10', 'HLSU-1010', '1');
INSERT INTO `product_contains` VALUES('5ac2a70bc37bb', 'HLFP-HT10', 'HLSP-AF10', '1');
INSERT INTO `product_contains` VALUES('5ac2a70bc3d94', 'HLFP-HT10', 'HLSP-FP10', '1');
INSERT INTO `product_contains` VALUES('5ac2a70bc6af9', 'HLFP-HT10', 'HLSP-MC32', '1');
INSERT INTO `product_contains` VALUES('5ac2a70bc97cb', 'HLFP-HT10', 'HLSP-PB10', '1');
INSERT INTO `product_contains` VALUES('5ac2a70bcc634', 'HLFP-HT10', 'HLSP-SC42', '4');
INSERT INTO `product_contains` VALUES('5ac2a70bcf1aa', 'HLFP-HT10', 'HLSP-SO10', '1');
INSERT INTO `product_contains` VALUES('5ac2a70bd4ac7', 'HLFP-HT10', 'HLRW-9912', '1');
INSERT INTO `product_contains` VALUES('5ac2a70bd7abc', 'HLFP-HT10', 'HLSU-1010', '1');
CREATE TABLE `products` (  `number` varchar(50) COLLATE utf8_unicode_ci NOT NULL,  `name` varchar(100) COLLATE utf8_unicode_ci NOT NULL,  `description` text COLLATE utf8_unicode_ci NOT NULL,  `unit` varchar(10) COLLATE utf8_unicode_ci NOT NULL,  `price` float NOT NULL,  `per_item` float NOT NULL,  `order_size` float NOT NULL,  `production_company` varchar(150) COLLATE utf8_unicode_ci NOT NULL,  `retail_company` varchar(150) COLLATE utf8_unicode_ci NOT NULL,  `link` text COLLATE utf8_unicode_ci NOT NULL,  `comment` text COLLATE utf8_unicode_ci NOT NULL,  `resell_price` float NOT NULL,  `attributes` text COLLATE utf8_unicode_ci NOT NULL,  PRIMARY KEY (`number`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
INSERT INTO `products` VALUES('HLFP-HT10', 'HiLight Home Theater', 'HiLight Home-Theater Set', 'Stk.', '0', '0', '0', '', '', '', '', '150', '');
INSERT INTO `products` VALUES('HLRW-1315', 'Klinkenbuchse Stereo', 'Klinkeneinbaubuchse\r\nStereo, 3-oplig\r\n2,5mm', 'Stk.', '0.97', '1', '50', 'Lumberg', 'Reichelt', 'https://www.reichelt.at/Klinkeneinbaubuchsen/LUM-1501-04/3/index.html?ACTION=3&LA=2&ARTICLE=116169&GROUPID=7448&artnr=LUM+1501-04&trstct=pol_38', '', '0', '');
INSERT INTO `products` VALUES('HLRW-1508', 'DIP-8 Sockel', 'IC-Sockel\r\nDoppelter Federkontakt', 'Stk.', '0.04', '1', '50', '', 'Reichelt', 'https://www.reichelt.at/IC-Sockel/GS-8/3/index.html?ACTION=3&LA=2&ARTICLE=8230&GROUPID=7429&artnr=GS+8&trstct=pol_74', '', '0', '');
INSERT INTO `products` VALUES('HLRW-1514', 'DIP-14 Sockel', 'IC-Sockel\r\nDoppelter Federkontakt', 'Stk.', '0.05', '1', '50', '', 'Reichelt', 'https://www.reichelt.at/IC-Sockel/GS-14/3/index.html?ACTION=3&LA=517&ARTICLE=8206&GROUPID=7429&trstct=lsbght_sldr::8230', '', '0', '');
INSERT INTO `products` VALUES('HLRW-1518', 'DIP-18 Sockel', 'IC-Sockel\r\nDoppelter Federkontakt', 'Stk.', '0.071', '1', '50', '', 'Reichelt', 'https://www.reichelt.at/IC-Sockel/GS-18/3/index.html?ACTION=3&LA=517&ARTICLE=8210&GROUPID=7429&trstct=lsbght_sldr::8206', '', '0', '');
INSERT INTO `products` VALUES('HLRW-2110', '10-Segemtn Anzeige', '10 Segment Anzeige\r\nRot', 'Stk.', '1.11', '1', '50', 'Kingbright', 'Reichelt', 'https://www.reichelt.at/Bargraf-LED-Anzeigen/RBG-1000/3/index.html?ACTION=3&LA=2&ARTICLE=15156&GROUPID=3016&artnr=RBG+1000&trstct=pol_6', '', '0', '');
INSERT INTO `products` VALUES('HLRW-2503', 'LED Blau 5mm', 'LED 5mm blau\r\n15° Abstrahlwinkel\r\nIvmax 25 mA', 'Stk.', '0.091', '1', '100', 'RND Components', 'Reichelt', 'https://www.reichelt.at/LEDs-5-mm/RND-135-00039/3/index.html?ACTION=3&LA=2&ARTICLE=224097&GROUPID=3019&artnr=RND+135-00039&trstct=pol_0', '', '0', '');
INSERT INTO `products` VALUES('HLRW-2510', 'LED RGB 5mm', 'RGB LED 5mm\r\nCommon Anode\r\nR + G B', 'Stk.', '7.67', '100', '1', 'GAOHU', 'Amazon', 'https://www.amazon.de/Stück-Ultra-Helle-Indirekt-Common/dp/B00H96MFNI', '', '0', '');
INSERT INTO `products` VALUES('HLRW-3210', 'Widerstand 1 kOhm', 'Widerstand, Metallschicht,\nNennlast 0,6W \n1% Toleranz\nReihe E96', 'Stk.', '0.025', '100', '1', 'YAGEO', 'Reichelt', 'https://www.reichelt.at/0-6W-1-1-00-k-Ohm-9-76-k-Ohm/METALL-1-00K/3/index.html?ACTION=3&LA=3&ARTICLE=11403&GROUPID=3078&trstct=vrt_pdn', '', '0', '');
INSERT INTO `products` VALUES('HLRW-3212', 'Widerstand 1,21 kOhm', 'Widerstand, Metallschicht,\r\nNennlast 0,6W \r\n1% Toleranz\r\nReihe E96', 'Stk.', '0.025', '100', '1', 'YAGEO', 'Reichelt', 'https://www.reichelt.at/0-6W-1-1-00-k-Ohm-9-76-k-Ohm/METALL-1-21K/3/index.html?ACTION=3&LA=3&ARTICLE=11417&GROUPID=3078&trstct=vrt_pdn', '', '0', '');
INSERT INTO `products` VALUES('HLRW-3220', 'Widerstand 2 kOhm', 'Widerstand, Metallschicht,\nNennlast 0,6W \n1% Toleranz\nReihe E96', 'Stk.', '0.025', '100', '1', 'YAGEO', 'Reichelt', 'https://www.reichelt.at/0-6W-1-1-00-k-Ohm-9-76-k-Ohm/METALL-2-00K/3/index.html?ACTION=3&LA=3&ARTICLE=11578&GROUPID=3078&trstct=vrt_pdn', '', '0', '');
INSERT INTO `products` VALUES('HLRW-3222', 'Widerstand 2,2 kOhm', 'Widerstand, Metallschicht,\nNennlast 0,6W \n1% Toleranz\nReihe E96', 'Stk.', '0.025', '100', '1', 'YAGEO', 'Reichelt', 'https://www.reichelt.at/0-6W-1-1-00-k-Ohm-9-76-k-Ohm/METALL-2-20K/3/index.html?ACTION=3&LA=3&ARTICLE=11584&GROUPID=3078&trstct=vrt_pdn', '', '0', '');
INSERT INTO `products` VALUES('HLRW-3238', 'Widerstand 3,83 kOhm', 'Widerstand, Metallschicht,\r\nNennlast 0,6W \r\n1% Toleranz\r\nReihe E96', 'Stk.', '0.025', '100', '1', 'YAGEO', 'Reichelt', 'https://www.reichelt.at/0-6W-1-1-00-k-Ohm-9-76-k-Ohm/METALL-3-83K/3/index.html?ACTION=3&LA=3&ARTICLE=11704&GROUPID=3078&trstct=vrt_pdn', '', '0', '');
INSERT INTO `products` VALUES('HLRW-3291', 'Widerstand 9,1 kOhm', 'Widerstand, Metallschicht,\nNennlast 0,6W \n1% Toleranz\nReihe E96', 'Stk.', '0.025', '100', '1', 'YAGEO', 'Reichelt', 'https://www.reichelt.at/0-6W-1-1-00-k-Ohm-9-76-k-Ohm/METALL-9-10K/3/index.html?ACTION=3&LA=3&ARTICLE=12021&GROUPID=3078&trstct=vrt_pdn', '', '0', '');
INSERT INTO `products` VALUES('HLRW-3310', 'Widerstand 10 kOhm', 'Widerstand, Metallschicht,\r\nNennlast 0,6W \r\n1% Toleranz\r\nReihe E96', 'Stk.', '0.025', '100', '1', 'YAGEO', 'Reichelt', 'https://www.reichelt.at/0-6W-1-10-0-k-Ohm-95-3-k-Ohm/METALL-10-0K/3/index.html?ACTION=3&LA=3&ARTICLE=11449&GROUPID=3079&trstct=vrt_pdn', '', '0', '');
INSERT INTO `products` VALUES('HLRW-3368', 'Widerstand 68 kOhm', 'Widerstand, Metallschicht,\nNennlast 0,6W \n1% Toleranz\nReihe E96', 'Stk.', '0.025', '100', '1', 'YAGEO', 'Reichelt', 'https://www.reichelt.at/0-6W-1-10-0-k-Ohm-95-3-k-Ohm/METALL-68-0K/3/index.html?ACTION=3&LA=3&ARTICLE=11939&GROUPID=3079&trstct=vrt_pdn', '', '0', '');
INSERT INTO `products` VALUES('HLRW-3710', 'Potentiometer 1 kOhm', 'Einstellpotentiometer,\r\nliegend', 'Stk.', '0.23', '1', '30', 'ACP', 'Reichelt', 'https://www.reichelt.at/ACP-Trimmer-9mm/ACP-9-L-1K/3/index.html?ACTION=3&LA=446&ARTICLE=110250&GROUPID=5260&artnr=ACP+9-L+1K&SEARCH=1k%2Bpotentiometer&trstct=pos_4', '', '0', '');
INSERT INTO `products` VALUES('HLRW-3810', 'Potentiometer 10 kOhm', 'Drehpotentiometer\r\n3-Pins', 'Stk.', '2', '10', '5', '', 'Wish', 'https://www.wish.com/search/potentiometer%2010k#cid=5511252f59c81210afaa1df1', '', '0', '');
INSERT INTO `products` VALUES('HLRW-4025', 'Transistor NPN 2N5551', 'Transisto NPN\r\nIc 600 mA\r\nPtot 0,63 W\r\nUces 160 V\r\nTO-92', 'Stk.', '0.04', '1', '100', 'HOTTECH', 'Reichelt', 'https://www.reichelt.at/2N-Transistoren/2N-5551/3/index.html?ACTION=3&LA=446&ARTICLE=2059&GROUPID=2879&artnr=2N+5551&SEARCH=2n5551&trstct=pos_0', '', '0', '');
INSERT INTO `products` VALUES('HLRW-5123', 'MOSFET TSM2312', 'N-Channel MOSFET\r\nSOT-23\r\nUDS 20V\r\nId 5A', 'Stk.', '0.26', '1', '100', 'TAIWAN-SEMICOND.', 'Reichelt', 'https://www.reichelt.at/MOSFET-Transistoren-IXYS/TSM-2312-SMD/3/index.html?ACTION=3&LA=446&ARTICLE=115909&GROUPID=4350&artnr=TSM+2312+SMD&SEARCH=Leistungs-MOSFET%2BN-Ch%2B20V%2B5A%2BSOT23&trstct=pos_0', '', '0', '');
INSERT INTO `products` VALUES('HLRW-6105', 'Keramikkondensator 1µF', 'Vielschicht Kerko\r\n1µF', 'Stk.', '0.67', '1', '50', 'KEMET', 'Reichelt', 'https://www.reichelt.at/Vielschicht-bedrahtet-X7R-10-/C3X7R-1-0U-50/3/index.html?ACTION=3&LA=2&ARTICLE=206882&GROUPID=3162&artnr=C3X7R+1%2C0U+50&trstct=pol_26', '', '0', '');
INSERT INTO `products` VALUES('HLRW-6222', 'Elektrolyt-Kondensator 2,2µF', 'Sumbiniatur-Elko\r\nradial\r\n2,2 µF\r\n50V', 'Stk.', '0.02', '1', '100', '', 'Reichelt', 'https://www.reichelt.at/Elkos-radial-subminiatur/SM-2-2-50RAD/3/index.html?ACTION=3&LA=446&ARTICLE=18165&GROUPID=3145&artnr=SM+2%2C2%2F50RAD&SEARCH=elko%2B2%252C2uF&trstct=pos_60', '', '0', '');
INSERT INTO `products` VALUES('HLRW-7140', 'Diode 1N4001', 'Gleichrichterdiode\r\n50V \r\n1A', 'Stk.', '0.02', '1', '100', 'LUNSURE', 'Reichelt', 'https://www.reichelt.at/1N-UF-AA-Dioden/1N-4001/3/index.html?ACTION=3&LA=446&ARTICLE=1723&GROUPID=2987&artnr=1N+4001&SEARCH=1N4001&trstct=pos_0', '', '0', '');
INSERT INTO `products` VALUES('HLRW-7158', 'Diode 1N5817', 'Schottky Diode\r\n20V \r\n1A', 'Stk.', '0.05', '1', '100', 'LUNSURE', 'Reichelt', 'https://www.reichelt.at/1N-UF-AA-Dioden/1N-5817/3/index.html?ACTION=3&LA=446&ARTICLE=41848&GROUPID=2987&artnr=1N+5817&SEARCH=1N5817&trstct=pos_0', '', '0', '');
INSERT INTO `products` VALUES('HLRW-8104', 'IC - Hex-Inverter 74AC04', 'IC-Schaltung\r\nHex-Inverter', 'Stk.', '0.29', '1', '50', 'Texas Instruments', 'Reichelt', 'https://www.reichelt.at/ICs-74HCT-DIL/74HCT-04/3/index.html?ACTION=3&LA=446&ARTICLE=3306&GROUPID=2932&artnr=74HCT+04&SEARCH=hex%2Binverter&trstct=pos_8', '', '0', '');
INSERT INTO `products` VALUES('HLRW-8213', 'IC - Zeitmesser DS1302', 'IC-Schaltung\r\nZeitmesser\r\nTrickle Charge', 'Stk.', '2.72', '1', '20', 'MAXIM', 'Reichelt', 'https://www.reichelt.at/ICs-CA-HV-/DS-1302/3/index.html?ACTION=3&LA=446&ARTICLE=7199&GROUPID=7209&artnr=DS+1302&SEARCH=DS1302&trstct=pos_0', '', '0', '');
INSERT INTO `products` VALUES('HLRW-8332', 'IC - Quad-Op Amp LM324N', 'IC-Schaltung\r\nOperationsverstärker\r\n4-fach', 'Stk.', '0.23', '1', '50', 'ST Microelectronics', 'Reichelt', 'https://www.reichelt.at/ICs-LM-10-LM-999/LM-324-DIL/3/index.html?ACTION=3&LA=446&ARTICLE=10463&GROUPID=5464&artnr=LM+324+DIL&SEARCH=lm324n&trstct=pos_0', '', '0', '');
INSERT INTO `products` VALUES('HLRW-8339', 'IC - Display-Treiber LM3914', 'IC-Schaltung\r\nDisplay-Treiber\r\nDot/Bar', 'Stk.', '2.01', '1', '40', 'Texas Instruments', 'Reichelt', 'https://www.reichelt.at/ICs-LM-2000-LM-25576/LM-3914-DIL/3/index.html?ACTION=3&LA=446&ARTICLE=10504&GROUPID=5466&artnr=LM+3914+DIL&SEARCH=lm3914&trstct=pos_0', '', '0', '');
INSERT INTO `products` VALUES('HLRW-9122', 'Touch Sensor', 'Touch Sensor \r\nCapacitive Touch Switch \r\nTTP223B', 'Stk.', '2', '1', '50', '', 'Wish', 'https://www.wish.com/search/Touch%20Sensor#cid=5abc7aed2d659f19ea490b2e', '', '0', '');
INSERT INTO `products` VALUES('HLRW-9132', 'Quarz 32768 Hz', 'Zeitmesser-Quarz\r\nFrequenz: 32.768 kHz', 'Stk.', '0.2', '1', '100', 'AURIS', 'Reichelt', 'https://www.reichelt.at/Uhrenquarze-SMD-Gehaeuse/0-032768/3/index.html?ACTION=3&LA=446&ARTICLE=1089&GROUPID=4005&artnr=0%2C032768&SEARCH=Mini%2BUhrenquarz%252C%2B0%252C032768%2BMHz%252C%2BTC38&trstct=pos_0', '', '0', '');
INSERT INTO `products` VALUES('HLRW-9146', 'I2C Screen Driver', 'I2C Serial Interface\r\nfor LCD Charakter Screen', 'Stk.', '2', '1', '10', '', 'Wish', 'https://www.wish.com/search/i2c#cid=573936d746d3725f0b130287', '', '0', '');
INSERT INTO `products` VALUES('HLRW-9236', 'Relais 5V-250V/10A', 'FIN 36.11 5V\r\nSubminiaturrelais\r\nWechsler', 'Stk.', '2.42', '1', '20', 'Finder', 'Reichelt', 'https://www.reichelt.at/Miniaturrelais/FIN-36-11-5V/3/index.html?ACTION=3&LA=446&ARTICLE=42373&GROUPID=7620&artnr=FIN+36.11+5V&SEARCH=5v%2Brelais&trstct=pos_1', '', '0', '');
INSERT INTO `products` VALUES('HLRW-9259', 'Step-Down-Converter', 'LM2596 DC to DC Step-Down \r\nTransformer Module Power Buck\r\nConverter', 'Stk.', '9', '10', '5', '', 'Wish', 'https://www.gearbest.com/development-boards/pp_51010.html?wid=21', '', '0', '');
INSERT INTO `products` VALUES('HLRW-9306', 'OLED LCD ', '0,96\" I2C Serial \r\nOLED LCD Screen', 'Stk.', '5', '1', '10', '', 'Wish', 'https://www.wish.com/c/590c80957c0ddf2d2f6d1d66', '', '0', '');
INSERT INTO `products` VALUES('HLRW-9320', 'Knopfzellenhalter Ø20mm', 'Knopfzellenhalter\r\nZellen: C2023', 'Stk.', '0.43', '1', '50', '', 'Reichelt', 'https://www.reichelt.at/Batteriehalter-fuer-Knopfzellen/KZH-20-1/3/index.html?ACTION=3&LA=446&ARTICLE=44621&GROUPID=4260&artnr=KZH+20-1&SEARCH=Knopfzellenhalter%2Bf%25C3%25BCr%2B%25C3%2598%2B20%2Bmm&trstct=pos_4', '', '0', '');
INSERT INTO `products` VALUES('HLRW-9323', 'Knopfzelle C2023', 'Knopfzellen\r\nTyp 2023\r\n3V 200 mAh', 'Stk.', '2.82', '6', '5', 'HyCell', 'Reichelt', 'https://www.reichelt.at/Knopfzellen-Lithium/HC-6XCR2032/3/index.html?ACTION=3&LA=2&ARTICLE=196265&GROUPID=4241&artnr=HC+6XCR2032&trstct=pol_12', '', '0', '');
INSERT INTO `products` VALUES('HLRW-9328', 'Arduino Nano', 'Arduino Nano\r\nV3.0\r\nMicrocontroller\r\nATMega328P', 'Stk.', '3', '1', '50', '', 'Wish', 'https://www.wish.com/search/arduino%20nano#cid=59e05db4642f1b2a728c73d1', '', '0', '');
INSERT INTO `products` VALUES('HLRW-9403', 'DIP-Schalter 3-polig', 'DIP-Schalter\r\nstehend\r\n3-polig', 'Stk.', '0.29', '1', '50', '', 'Reichelt', 'https://www.reichelt.at/Dip-Kodierschalter/NT-03/3/index.html?ACTION=3&LA=446&ARTICLE=36465&GROUPID=7598&artnr=NT+03&SEARCH=dip%2Bschalter&trstct=pos_80', '', '0', '');
INSERT INTO `products` VALUES('HLRW-9602', 'LCD Screen 16x2', 'LCD Charaker Screen\r\n16 Pins\r\nBacklight\r\n16x2 Charakters', 'Stk.', '2', '1', '10', '', 'Wish', 'https://www.wish.com/c/5915aa9c786f47666e0decb6', '', '0', '');
INSERT INTO `products` VALUES('HLRW-9812', 'Einbaubuchse Ø2,1mm', 'Einbaubuchse\r\n90° abgewinkelt\r\nStift Ø2,1mm', 'Stk.', '0.41', '1', '50', '', 'Reichelt', 'https://www.reichelt.at/Hohlstecker/DC-BU21-90/3/index.html?ACTION=3&LA=2&ARTICLE=183502&GROUPID=7488&artnr=DC+BU21+90&trstct=pol_3', '', '0', '');
INSERT INTO `products` VALUES('HLRW-9912', 'Netzteil 12V', 'Steckernetzteil\r\n12V\r\n3A\r\n36W\r\nHohlstecker Ø5,5/2,1', 'Stk.', '15.13', '1', '50', 'Mean Well', 'Reichelt', 'https://www.reichelt.at/Festspannungsnetzteile/GS36E12-P1J/3/index.html?ACTION=3&LA=2&ARTICLE=161626&GROUPID=4946&artnr=GS36E12-P1J&trstct=pol_0', '', '0', '');
INSERT INTO `products` VALUES('HLSP-AF10', 'Audio Faceplate', 'Faceplate für\r\nSoundsteuerplatine', 'Stk.', '0', '0', '0', '', '', '', '', '0', '');
INSERT INTO `products` VALUES('HLSP-FP10', 'I/O Faceplate', 'Faceplate für Steuerelemente', 'Stk.', '0', '0', '0', '', '', '', '', '0', '');
INSERT INTO `products` VALUES('HLSP-MC32', 'Main Controller', 'Hauptsteuerplatine\r\nfür HiLight System', 'Stk.', '0', '0', '0', '', '', '', '', '0', '');
INSERT INTO `products` VALUES('HLSP-PB10', 'Power Board', 'Stromverteilplatine', 'Stk.', '0', '0', '0', '', '', '', '', '0', '');
INSERT INTO `products` VALUES('HLSP-SC42', 'Strip Controller', 'LED-Streifen\r\nSteuerplatine', 'Stk.', '0', '0', '0', '', '', '', '', '0', '');
INSERT INTO `products` VALUES('HLSP-SO10', 'Sound Controller', 'Musiksteuerplatine', 'Stk.', '0', '0', '0', '', '', '', '', '0', '');
INSERT INTO `products` VALUES('HLSU-1010', 'Lötzinn Ø0,5', 'Lötzinn Bleihalting Ø0,5mm\r\n- Flußmittelanteil: 2% \r\n- Schmelzpunkt 182°C', 'g', '6.04', '100', '1', 'FIXPOINT', 'Reichelt', 'https://www.reichelt.at/Loetzinn/LZ-FP-0-5-100/3/index.html?ACTION=3&LA=446&ARTICLE=153161&GROUPID=557&artnr=LZ+FP+0%2C5+100&SEARCH=l%25C3%25B6tzinn&trstct=pos_11', '', '0', '');
INSERT INTO `products` VALUES('HLSU-1020', 'Entlötlitze 0,8mm', 'Entlötlitze Kupfer\r\n1,5m x 0,8mm', 'Stk.', '7.41', '1', '1', 'CRC-Kontaktchemie', 'Reichelt', 'https://www.reichelt.at/Entloetpumpen-Entloetlitze/SOLDASORB-08/3/index.html?ACTION=3&LA=446&ARTICLE=122317&GROUPID=556&artnr=SOLDASORB+08&SEARCH=entl%25C3%25B6t&trstct=pos_7', '', '0', '');
CREATE TABLE `protocol` (  `id` varchar(13) CHARACTER SET latin1 NOT NULL,  `user` varchar(13) CHARACTER SET latin1 NOT NULL,  `date` varchar(50) CHARACTER SET latin1 NOT NULL,  `description` text CHARACTER SET latin1 NOT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
INSERT INTO `protocol` VALUES('5abb5d8c9f044', '59ce8c11b145c', 'Wed Mar 28 2018 11:17:00 ', 'Tobias Hattinger hat sich eingeloggt.');
INSERT INTO `protocol` VALUES('5abb5e27ea479', '59ce8c11b145c', 'Wed Mar 28 2018 11:19:35 ', 'Produkt \"WEA-RES2k2\" wurde zum Lager hinzugefügt.');
INSERT INTO `protocol` VALUES('5abb5e4eb1c52', '59ce8c11b145c', 'Wed Mar 28 2018 11:20:14 ', 'Produkt \"WEA-TRS2N2222\" wurde zum Lager hinzugefügt.');
INSERT INTO `protocol` VALUES('5abb5e8cb6e85', '59ce8c11b145c', 'Wed Mar 28 2018 11:21:16 ', 'Produktdaten des Produkts \"WECP-HLMICRO\" wurden aktualisiert.');
INSERT INTO `protocol` VALUES('5abb5e9129d53', '59ce8c11b145c', 'Wed Mar 28 2018 11:21:21 ', 'Item \"WEA-RES2k2\" wurde dem Produkt \"WECP-HLMICRO\" angefügt.');
INSERT INTO `protocol` VALUES('5abb5e93228c4', '59ce8c11b145c', 'Wed Mar 28 2018 11:21:23 ', 'Item \"WEA-RES2k2\" wurde dem Produkt \"WECP-HLMICRO\" angefügt.');
INSERT INTO `protocol` VALUES('5abb5e941fed8', '59ce8c11b145c', 'Wed Mar 28 2018 11:21:24 ', 'Item \"WEA-RES2k2\" wurde dem Produkt \"WECP-HLMICRO\" angefügt.');
INSERT INTO `protocol` VALUES('5abb5e9542040', '59ce8c11b145c', 'Wed Mar 28 2018 11:21:25 ', 'Item \"WEA-RES2k2\" wurde dem Produkt \"WECP-HLMICRO\" angefügt.');
INSERT INTO `protocol` VALUES('5abb5e96466c7', '59ce8c11b145c', 'Wed Mar 28 2018 11:21:26 ', 'Item \"WEA-RES2k2\" wurde dem Produkt \"WECP-HLMICRO\" angefügt.');
INSERT INTO `protocol` VALUES('5abb5e9941da4', '59ce8c11b145c', 'Wed Mar 28 2018 11:21:29 ', 'Item \"WEA-TRS2N2222\" wurde dem Produkt \"WECP-HLMICRO\" angefügt.');
CREATE TABLE `settings` (  `setting` varchar(200) NOT NULL,  `value` varchar(200) NOT NULL,  PRIMARY KEY (`setting`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
INSERT INTO `settings` VALUES('def_lang_erp', 'DE');
INSERT INTO `settings` VALUES('prefix_product', 'HLFP');
INSERT INTO `settings` VALUES('prefix_raw', 'HLRW');
INSERT INTO `settings` VALUES('prefix_semiproduct', 'HLSP');
INSERT INTO `settings` VALUES('prefix_support', 'HLSU');
CREATE TABLE `shipping` (  `id` varchar(13) NOT NULL,  `product_nr` varchar(15) NOT NULL,  `description` varchar(255) NOT NULL,  `price` float NOT NULL,  `weight` float NOT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `timestamp` (  `id` varchar(13) COLLATE utf8_unicode_ci NOT NULL,  `user_id` varchar(13) COLLATE utf8_unicode_ci NOT NULL,  `come` datetime NOT NULL,  `go` datetime NOT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `users` (  `id` varchar(13) COLLATE utf8_unicode_ci NOT NULL,  `first_name` varchar(50) COLLATE utf8_unicode_ci NOT NULL,  `last_name` varchar(50) COLLATE utf8_unicode_ci NOT NULL,  `email` varchar(100) COLLATE utf8_unicode_ci NOT NULL,  `password` varchar(100) COLLATE utf8_unicode_ci NOT NULL,  `stamped` tinyint(1) NOT NULL,  `current_ts_id` varchar(13) COLLATE utf8_unicode_ci NOT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
INSERT INTO `users` VALUES('59ce8c11b145c', 'Tobias', 'Hattinger', 'tobias.hattinger@wepen.at', 'c7b308c7ebc6def0ad3509bfebed14ca9a4fb8b6', '0', '5a97a133d41fd');
